// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Connection struct
 */
export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (!("authMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authMethod"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["passphrase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 服务器分组，空=未分组
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["os"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ponytail: 非空时用 Credential 认证，忽略内联字段
             * @member
             * @type {string | undefined}
             */
            this["credentialId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["terminalInitPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fileManagerInitPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["terminalEncoding"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["allowLegacySshRsa"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxyMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxyNodeId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxyType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxyHost"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["proxyPort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxyUsername"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxyPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Unix 毫秒时间戳，合并时判断新旧
             * @member
             * @type {number | undefined}
             */
            this["last_modified"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * Credential 可复用的认证凭据，多个 Connection 可引用同一 Credential
 */
export class Credential {
    /**
     * Creates a new Credential instance.
     * @param {Partial<Credential>} [$$source = {}] - The source object to create the Credential.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("authMethod" in $$source)) {
            /**
             * "password" | "privateKey"
             * @member
             * @type {string}
             */
            this["authMethod"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 加密存储
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 加密存储
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 加密存储
             * @member
             * @type {string | undefined}
             */
            this["passphrase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Unix 毫秒时间戳
             * @member
             * @type {number | undefined}
             */
            this["last_modified"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Credential instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Credential}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Credential(/** @type {Partial<Credential>} */($$parsedSource));
    }
}

export class FTPCertificateInfo {
    /**
     * Creates a new FTPCertificateInfo instance.
     * @param {Partial<FTPCertificateInfo>} [$$source = {}] - The source object to create the FTPCertificateInfo.
     */
    constructor($$source = {}) {
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pinnedFingerprint"] = undefined;
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("issuer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["issuer"] = "";
        }
        if (!("serialNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serialNumber"] = "";
        }
        if (!("dnsNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dnsNames"] = [];
        }
        if (!("ipAddresses" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ipAddresses"] = [];
        }
        if (!("notBefore" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notBefore"] = "";
        }
        if (!("notAfter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notAfter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FTPCertificateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FTPCertificateInfo}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dnsNames" in $$parsedSource) {
            $$parsedSource["dnsNames"] = $$createField6_0($$parsedSource["dnsNames"]);
        }
        if ("ipAddresses" in $$parsedSource) {
            $$parsedSource["ipAddresses"] = $$createField7_0($$parsedSource["ipAddresses"]);
        }
        return new FTPCertificateInfo(/** @type {Partial<FTPCertificateInfo>} */($$parsedSource));
    }
}

export class FTPConnectionTestResult {
    /**
     * Creates a new FTPConnectionTestResult instance.
     * @param {Partial<FTPConnectionTestResult>} [$$source = {}] - The source object to create the FTPConnectionTestResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FTPCertificateInfo | null | undefined}
             */
            this["certificateApprovalRequired"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FTPConnectionTestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FTPConnectionTestResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("certificateApprovalRequired" in $$parsedSource) {
            $$parsedSource["certificateApprovalRequired"] = $$createField1_0($$parsedSource["certificateApprovalRequired"]);
        }
        return new FTPConnectionTestResult(/** @type {Partial<FTPConnectionTestResult>} */($$parsedSource));
    }
}

/**
 * ImportResult 导入操作的统计结果
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * 文件中的节点总数
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("imported" in $$source)) {
            /**
             * 实际新增数
             * @member
             * @type {number}
             */
            this["imported"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * 跳过的重复数
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("details" in $$source)) {
            /**
             * 被跳过的节点明细
             * @member
             * @type {skippedItem[]}
             */
            this["details"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField3_0($$parsedSource["details"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

export class SFTPConnectionTestResult {
    /**
     * Creates a new SFTPConnectionTestResult instance.
     * @param {Partial<SFTPConnectionTestResult>} [$$source = {}] - The source object to create the SFTPConnectionTestResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SFTPHostKeyMismatch | null | undefined}
             */
            this["hostKeyMismatch"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPConnectionTestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SFTPConnectionTestResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostKeyMismatch" in $$parsedSource) {
            $$parsedSource["hostKeyMismatch"] = $$createField1_0($$parsedSource["hostKeyMismatch"]);
        }
        return new SFTPConnectionTestResult(/** @type {Partial<SFTPConnectionTestResult>} */($$parsedSource));
    }
}

export class SFTPHostKeyMismatch {
    /**
     * Creates a new SFTPHostKeyMismatch instance.
     * @param {Partial<SFTPHostKeyMismatch>} [$$source = {}] - The source object to create the SFTPHostKeyMismatch.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("newFingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["newFingerprint"] = "";
        }
        if (!("oldFingerprints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["oldFingerprints"] = [];
        }
        if (!("knownHostsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["knownHostsPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPHostKeyMismatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SFTPHostKeyMismatch}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("oldFingerprints" in $$parsedSource) {
            $$parsedSource["oldFingerprints"] = $$createField2_0($$parsedSource["oldFingerprints"]);
        }
        return new SFTPHostKeyMismatch(/** @type {Partial<SFTPHostKeyMismatch>} */($$parsedSource));
    }
}

/**
 * SyncTombstonePruneResult 按天数清理墓碑的结果。
 */
export class SyncTombstonePruneResult {
    /**
     * Creates a new SyncTombstonePruneResult instance.
     * @param {Partial<SyncTombstonePruneResult>} [$$source = {}] - The source object to create the SyncTombstonePruneResult.
     */
    constructor($$source = {}) {
        if (!("removedConnections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removedConnections"] = 0;
        }
        if (!("removedCredentials" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removedCredentials"] = 0;
        }
        if (!("remainingConnections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remainingConnections"] = 0;
        }
        if (!("remainingCredentials" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remainingCredentials"] = 0;
        }
        if (!("uploaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uploaded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncTombstonePruneResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncTombstonePruneResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncTombstonePruneResult(/** @type {Partial<SyncTombstonePruneResult>} */($$parsedSource));
    }
}

/**
 * SyncTombstoneStats 同步删除记录条数（供设置页展示）。
 */
export class SyncTombstoneStats {
    /**
     * Creates a new SyncTombstoneStats instance.
     * @param {Partial<SyncTombstoneStats>} [$$source = {}] - The source object to create the SyncTombstoneStats.
     */
    constructor($$source = {}) {
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections"] = 0;
        }
        if (!("credentials" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["credentials"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncTombstoneStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncTombstoneStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncTombstoneStats(/** @type {Partial<SyncTombstoneStats>} */($$parsedSource));
    }
}

/**
 * TombstoneConflictItem 预检：本地墓碑会从目标云删掉的项。
 */
export class TombstoneConflictItem {
    /**
     * Creates a new TombstoneConflictItem instance.
     * @param {Partial<TombstoneConflictItem>} [$$source = {}] - The source object to create the TombstoneConflictItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TombstoneConflictItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TombstoneConflictItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TombstoneConflictItem(/** @type {Partial<TombstoneConflictItem>} */($$parsedSource));
    }
}

/**
 * TombstoneConflictPreview 合并同步前预检结果：先读远端再算「墓碑 ∩ 远端仍在」。
 */
export class TombstoneConflictPreview {
    /**
     * Creates a new TombstoneConflictPreview instance.
     * @param {Partial<TombstoneConflictPreview>} [$$source = {}] - The source object to create the TombstoneConflictPreview.
     */
    constructor($$source = {}) {
        if (!("providers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["providers"] = [];
        }
        if (!("wouldDeleteConnections" in $$source)) {
            /**
             * @member
             * @type {TombstoneConflictItem[]}
             */
            this["wouldDeleteConnections"] = [];
        }
        if (!("wouldDeleteCredentials" in $$source)) {
            /**
             * @member
             * @type {TombstoneConflictItem[]}
             */
            this["wouldDeleteCredentials"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TombstoneConflictPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TombstoneConflictPreview}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField0_0($$parsedSource["providers"]);
        }
        if ("wouldDeleteConnections" in $$parsedSource) {
            $$parsedSource["wouldDeleteConnections"] = $$createField1_0($$parsedSource["wouldDeleteConnections"]);
        }
        if ("wouldDeleteCredentials" in $$parsedSource) {
            $$parsedSource["wouldDeleteCredentials"] = $$createField2_0($$parsedSource["wouldDeleteCredentials"]);
        }
        return new TombstoneConflictPreview(/** @type {Partial<TombstoneConflictPreview>} */($$parsedSource));
    }
}

/**
 * skippedItem 记录导入时被跳过（本地已存在）的节点信息
 */
export class skippedItem {
    /**
     * Creates a new skippedItem instance.
     * @param {Partial<skippedItem>} [$$source = {}] - The source object to create the skippedItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new skippedItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {skippedItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new skippedItem(/** @type {Partial<skippedItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FTPCertificateInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = skippedItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SFTPHostKeyMismatch.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = TombstoneConflictItem.createFrom;
const $$createType8 = $Create.Array($$createType7);
