// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../ai/models.js";

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function ApproveAIChatTools(requestID) {
    return $Call.ByID(59000861, requestID);
}

/**
 * @param {string} requestID
 * @param {string} targetSessionID
 * @returns {$CancellablePromise<void>}
 */
export function AssignAIChatToolTerminal(requestID, targetSessionID) {
    return $Call.ByID(185030762, requestID, targetSessionID);
}

/**
 * @param {string} sessionID
 * @param {string} snapshotJSON
 * @returns {$CancellablePromise<ai$0.AIConversationTokenLedger>}
 */
export function BuildAIConversationTokenLedger(sessionID, snapshotJSON) {
    return $Call.ByID(2006322302, sessionID, snapshotJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function CancelAIChat(requestID) {
    return $Call.ByID(209992119, requestID);
}

/**
 * @param {string} conversationID
 * @param {string} sessionID
 * @returns {$CancellablePromise<ai$0.AIConversationContextCondenseResult>}
 */
export function CondenseAIConversationContext(conversationID, sessionID) {
    return $Call.ByID(1600852754, conversationID, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function ContinueAIChatTool(requestID) {
    return $Call.ByID(3605485866, requestID);
}

/**
 * @param {string} sessionID
 * @param {string} conversationID
 * @param {string} messagesJSON
 * @returns {$CancellablePromise<ai$0.AIConversationAPIMessageTokenEntry[]>}
 */
export function CountAIConversationAPIMessageRawTokens(sessionID, conversationID, messagesJSON) {
    return $Call.ByID(1845752858, sessionID, conversationID, messagesJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} snapshotJSON
 * @returns {$CancellablePromise<ai$0.AIConversationContextMetrics>}
 */
export function CountAIConversationContextTokens(sessionID, snapshotJSON) {
    return $Call.ByID(3496656966, sessionID, snapshotJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<ai$0.AIConversationSnapshot>}
 */
export function CreateAIConversation(title) {
    return $Call.ByID(3609717956, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} conversationID
 * @param {string} sessionID
 * @param {string} requestID
 * @returns {$CancellablePromise<ai$0.AIConversationSummarySubtaskResult>}
 */
export function CreateAIConversationSummarySubtask(conversationID, sessionID, requestID) {
    return $Call.ByID(3900065155, conversationID, sessionID, requestID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAIConversation(conversationID) {
    return $Call.ByID(460513443, conversationID);
}

/**
 * @param {string} conversationID
 * @param {string} backupID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAIConversationBackup(conversationID, backupID) {
    return $Call.ByID(3876719953, conversationID, backupID);
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function DisableAIChatCollaboration(requestID) {
    return $Call.ByID(3337141736, requestID);
}

/**
 * @param {string} language
 * @returns {$CancellablePromise<string>}
 */
export function GetAIAssistantFirstReply(language) {
    return $Call.ByID(3206196301, language);
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<ai$0.AIConversationSnapshot>}
 */
export function GetAIConversation(conversationID) {
    return $Call.ByID(267415838, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} conversationID
 * @param {string} backupID
 * @returns {$CancellablePromise<ai$0.AIConversationAPIMessage[]>}
 */
export function GetAIConversationBackupHistory(conversationID, backupID) {
    return $Call.ByID(1576162784, conversationID, backupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<ai$0.AIGlobalSettings>}
 */
export function GetAIGlobalSettings() {
    return $Call.ByID(3038856499).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<ai$0.AIProviderState>}
 */
export function GetAIProviderState() {
    return $Call.ByID(1526470201).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<string>}
 */
export function GetAIProviderTokenGroup(jsonStr) {
    return $Call.ByID(1874568920, jsonStr);
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<ai$0.AIChatCommandTerminalCandidate[]>}
 */
export function ListAIChatCommandTerminalCandidates(requestID) {
    return $Call.ByID(1976405788, requestID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<ai$0.AIConversationBackup[]>}
 */
export function ListAIConversationBackups(conversationID) {
    return $Call.ByID(1402450591, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<ai$0.AIConversationSummary[]>}
 */
export function ListAIConversations() {
    return $Call.ByID(3730756945).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<void>}
 */
export function OpenAIConversationFolder(conversationID) {
    return $Call.ByID(2186094460, conversationID);
}

/**
 * @param {string} conversationID
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function PreprocessAIConversationLongText(conversationID, text) {
    return $Call.ByID(1126994155, conversationID, text);
}

/**
 * @param {string} reviewID
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function PreviewAIChatToolDiff(reviewID, sessionID) {
    return $Call.ByID(1536286106, reviewID, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} reviewID
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function PreviewAIChatToolRestore(reviewID, sessionID) {
    return $Call.ByID(3481920785, reviewID, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} conversationID
 * @param {string} sessionID
 * @returns {$CancellablePromise<ai$0.AIConversationContextCondenseResult>}
 */
export function PreviewAIConversationContextCondense(conversationID, sessionID) {
    return $Call.ByID(3381507598, conversationID, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} conversationID
 * @param {string} sessionID
 * @param {string} requestID
 * @returns {$CancellablePromise<boolean>}
 */
export function ProbeAIProviderLiveness(conversationID, sessionID, requestID) {
    return $Call.ByID(3111511639, conversationID, sessionID, requestID);
}

/**
 * @param {string} conversationID
 * @param {string} localPath
 * @returns {$CancellablePromise<string>}
 */
export function ReadAIConversationWrappedFile(conversationID, localPath) {
    return $Call.ByID(587219959, conversationID, localPath);
}

/**
 * @param {string} reviewID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function ReapplyAIChatTool(reviewID, sessionID) {
    return $Call.ByID(2751068706, reviewID, sessionID);
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function RejectAIChatTools(requestID) {
    return $Call.ByID(837051937, requestID);
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function RejectAIChatToolsForQueuedSubmission(requestID) {
    return $Call.ByID(1006704849, requestID);
}

/**
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<string[]>}
 */
export function RequestAIProviderModels(baseURL, apiKey) {
    return $Call.ByID(2996218399, baseURL, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<string[]>}
 */
export function RequestAIProviderModelsWithProfile(jsonStr) {
    return $Call.ByID(3673575608, jsonStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} requestID
 * @param {string} answer
 * @param {string} imagesJSON
 * @returns {$CancellablePromise<void>}
 */
export function ResolveAIChatFollowup(requestID, answer, imagesJSON) {
    return $Call.ByID(117001031, requestID, answer, imagesJSON);
}

/**
 * @param {string} reviewID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function RestoreAIChatTool(reviewID, sessionID) {
    return $Call.ByID(535554387, reviewID, sessionID);
}

/**
 * @param {string} conversationID
 * @param {string} backupID
 * @returns {$CancellablePromise<ai$0.AIConversationSnapshot>}
 */
export function RestoreAIConversationBackup(conversationID, backupID) {
    return $Call.ByID(1147885870, conversationID, backupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<ai$0.AIConversationSnapshot>}
 */
export function SaveAIConversation(jsonStr) {
    return $Call.ByID(2089018945, jsonStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveAIGlobalSettings(jsonStr) {
    return $Call.ByID(16432848, jsonStr);
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveAIProviderState(jsonStr) {
    return $Call.ByID(1540857344, jsonStr);
}

/**
 * @param {string} query
 * @param {string} conversationID
 * @param {number} limit
 * @returns {$CancellablePromise<ai$0.AIConversationMessageSearchResult[]>}
 */
export function SearchAIConversationMessages(query, conversationID, limit) {
    return $Call.ByID(4171668804, query, conversationID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {string} requestID
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAIChatSkipNextAutomaticRequest(requestID, enabled) {
    return $Call.ByID(400204517, requestID, enabled);
}

/**
 * @param {string} requestID
 * @param {string} messagesJSON
 * @returns {$CancellablePromise<void>}
 */
export function StartAIChat(requestID, messagesJSON) {
    return $Call.ByID(2607093859, requestID, messagesJSON);
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function StartAIChatCollaboration(requestID) {
    return $Call.ByID(2282226596, requestID);
}

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function TerminateAIChatTool(requestID) {
    return $Call.ByID(3517113986, requestID);
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<ai$0.AIProviderWebSearchValidationResult>}
 */
export function ValidateAIProviderWebSearch(jsonStr) {
    return $Call.ByID(2392488054, jsonStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

// Private type creation functions
const $$createType0 = ai$0.AIConversationTokenLedger.createFrom;
const $$createType1 = ai$0.AIConversationContextCondenseResult.createFrom;
const $$createType2 = ai$0.AIConversationAPIMessageTokenEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ai$0.AIConversationContextMetrics.createFrom;
const $$createType5 = ai$0.AIConversationSnapshot.createFrom;
const $$createType6 = ai$0.AIConversationSummarySubtaskResult.createFrom;
const $$createType7 = ai$0.AIConversationAPIMessage.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ai$0.AIGlobalSettings.createFrom;
const $$createType10 = ai$0.AIProviderState.createFrom;
const $$createType11 = ai$0.AIChatCommandTerminalCandidate.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ai$0.AIConversationBackup.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ai$0.AIConversationSummary.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = ai$0.AIConversationMessageSearchResult.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = ai$0.AIProviderWebSearchValidationResult.createFrom;
