// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../ai/models.js";

/**
 * @returns {$CancellablePromise<ai$0.AIProviderState>}
 */
export function GetAIProviderState() {
    return $Call.ByID(927133438).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveAIProviderState(jsonStr) {
    return $Call.ByID(2149802137, jsonStr);
}

// Private type creation functions
const $$createType0 = ai$0.AIProviderState.createFrom;
