// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpserver$0 from "../mcpserver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as programfonts$0 from "../programfonts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sshmanager$0 from "../sshmanager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtimeenv$0 from "../../module/runtimeenv/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} taskID
 * @param {string} fileID
 * @returns {$CancellablePromise<void>}
 */
export function AbortChunkedUploadFile(taskID, fileID) {
    return $Call.ByID(722211055, taskID, fileID);
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function AbortChunkedUploadTask(taskID) {
    return $Call.ByID(2354400552, taskID);
}

/**
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function AbortCompressedUpload(sessionId) {
    return $Call.ByID(3958912856, sessionId);
}

/**
 * @param {string} identifier
 * @returns {$CancellablePromise<void>}
 */
export function AbortDownloadTransfer(identifier) {
    return $Call.ByID(3954525431, identifier);
}

/**
 * AcceptHostKeyChange 用户确认主机密钥变更
 * action: 0=取消, 1=仅本次接受, 2=接受并保存
 * @param {string} sessionId
 * @param {number} action
 * @returns {$CancellablePromise<void>}
 */
export function AcceptHostKeyChange(sessionId, action) {
    return $Call.ByID(3291439847, sessionId, action);
}

/**
 * AckClose 前端响应了关闭弹窗（tray/cancel），取消 5s 兜底强制退出
 * @returns {$CancellablePromise<void>}
 */
export function AckClose() {
    return $Call.ByID(2445924029);
}

/**
 * @param {string} sessionId
 * @param {string[]} localPaths
 * @param {string} remoteDir
 * @returns {$CancellablePromise<void>}
 */
export function AutoRepairCompressedUploadTargets(sessionId, localPaths, remoteDir) {
    return $Call.ByID(1880633310, sessionId, localPaths, remoteDir);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function BackupToFTP() {
    return $Call.ByID(2016818229).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function BackupToR2() {
    return $Call.ByID(232635861).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function BackupToSFTP() {
    return $Call.ByID(1287643160).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function BackupToWebdav() {
    return $Call.ByID(2448642916).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BatchDeleteConnections removes multiple connections at once
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function BatchDeleteConnections(ids) {
    return $Call.ByID(539449242, ids);
}

/**
 * BatchDeleteItemShell 用一条rm -rf path1 path2 ... 批量删除
 * @param {string} sessionId
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function BatchDeleteItemShell(sessionId, paths) {
    return $Call.ByID(1636832188, sessionId, paths);
}

/**
 * BatchSetConnectionGroup 批量更新服务器分组
 * @param {string[]} ids
 * @param {string} group
 * @returns {$CancellablePromise<void>}
 */
export function BatchSetConnectionGroup(ids, group) {
    return $Call.ByID(554830653, ids, group);
}

/**
 * @param {string} taskID
 * @param {string} relativePath
 * @param {number} size
 * @param {number} totalChunks
 * @returns {$CancellablePromise<string>}
 */
export function BeginChunkedUploadFile(taskID, relativePath, size, totalChunks) {
    return $Call.ByID(111939770, taskID, relativePath, size, totalChunks);
}

/**
 * @param {string} sessionId
 * @param {string} remoteDir
 * @param {number} maxClients
 * @returns {$CancellablePromise<string>}
 */
export function BeginChunkedUploadTask(sessionId, remoteDir, maxClients) {
    return $Call.ByID(874061913, sessionId, remoteDir, maxClients);
}

/**
 * @param {string} providerID
 * @returns {$CancellablePromise<void>}
 */
export function CancelBuiltinProviderInitialization(providerID) {
    return $Call.ByID(2684845514, providerID);
}

/**
 * @param {string} newPassword
 * @returns {$CancellablePromise<void>}
 */
export function ChangeRecoveryPassword(newPassword) {
    return $Call.ByID(530240868, newPassword);
}

/**
 * ChmodFile changes file permissions via SFTP or recursively via chmod -R
 * @param {string} sessionId
 * @param {string} path
 * @param {string} mode
 * @param {boolean} recursive
 * @returns {$CancellablePromise<void>}
 */
export function ChmodFile(sessionId, path, mode, recursive) {
    return $Call.ByID(628344009, sessionId, path, mode, recursive);
}

/**
 * @param {string} sessionId
 * @param {string} path
 * @param {string} owner
 * @param {string} group
 * @param {boolean} recursive
 * @returns {$CancellablePromise<void>}
 */
export function ChownFile(sessionId, path, owner, group, recursive) {
    return $Call.ByID(4234774797, sessionId, path, owner, group, recursive);
}

/**
 * CleanupWsPending 在会话彻底销毁时清理其注册前缓冲，避免 pending map 残留。
 * 注意：不能在单条 WS 重连时调用——重连期间 PTY 可能仍在向 pending 缓冲首帧，
 * 那些数据需要留给新连接 flush。仅在 session 彻底断开时调用。
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function CleanupWsPending(sessionId) {
    return $Call.ByID(4029634095, sessionId);
}

/**
 * ClearTombstoneConflicts 放弃删除意图（保留云端项）后应再执行合并同步。
 * @param {string[]} connectionIDs
 * @param {string[]} credentialIDs
 * @returns {$CancellablePromise<void>}
 */
export function ClearTombstoneConflicts(connectionIDs, credentialIDs) {
    return $Call.ByID(421443029, connectionIDs, credentialIDs);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearWorkspaceState() {
    return $Call.ByID(2700711037);
}

/**
 * @param {string} taskID
 * @param {string} fileID
 * @returns {$CancellablePromise<void>}
 */
export function CompleteChunkedUploadFile(taskID, fileID) {
    return $Call.ByID(1465596092, taskID, fileID);
}

/**
 * CompressItem archives a file or directory on the remote server
 * @param {string} sessionId
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function CompressItem(sessionId, remotePath) {
    return $Call.ByID(3087947105, sessionId, remotePath);
}

/**
 * ConnectLocal spawns a local command process and pipes it to the WebSocket path.
 * @param {string} sessionId
 * @param {string} name
 * @param {string} shellPath
 * @param {string} cwd
 * @returns {$CancellablePromise<void>}
 */
export function ConnectLocal(sessionId, name, shellPath, cwd) {
    return $Call.ByID(1802834403, sessionId, name, shellPath, cwd);
}

/**
 * ConnectSSH establishes an SSH connection
 * @param {string} sessionId
 * @param {string} connId
 * @returns {$CancellablePromise<void>}
 */
export function ConnectSSH(sessionId, connId) {
    return $Call.ByID(1346818010, sessionId, connId);
}

/**
 * ConnectSerial connects to a local serial port and pipes it to the WebSocket path.
 * @param {string} sessionId
 * @param {string} name
 * @param {string} portName
 * @param {number} baudRate
 * @param {number} dataBits
 * @param {number} stopBits
 * @param {string} parity
 * @returns {$CancellablePromise<void>}
 */
export function ConnectSerial(sessionId, name, portName, baudRate, dataBits, stopBits, parity) {
    return $Call.ByID(103033916, sessionId, name, portName, baudRate, dataBits, stopBits, parity);
}

/**
 * CopyItem copies a file or directory within the same server (server-local cp -a).
 * @param {string} sessionId
 * @param {string} srcPath
 * @param {string} dstPath
 * @returns {$CancellablePromise<void>}
 */
export function CopyItem(sessionId, srcPath, dstPath) {
    return $Call.ByID(3741453008, sessionId, srcPath, dstPath);
}

/**
 * @param {string} themeID
 * @param {string} targetMode
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function CopyThemePackageToMode(themeID, targetMode) {
    return $Call.ByID(581577886, themeID, targetMode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteConnection removes a connection by ID
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(262495081, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCredential(id) {
    return $Call.ByID(53893288, id);
}

/**
 * DeleteItem deletes a file or directory via SFTP
 * @param {string} sessionId
 * @param {string} path
 * @param {boolean} isDir
 * @returns {$CancellablePromise<void>}
 */
export function DeleteItem(sessionId, path, isDir) {
    return $Call.ByID(680995574, sessionId, path, isDir);
}

/**
 * DeleteItemShell 用 rm -rf 删除
 * @param {string} sessionId
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteItemShell(sessionId, path) {
    return $Call.ByID(3878308264, sessionId, path);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMCPGlobalServer(name) {
    return $Call.ByID(2203637203, name);
}

/**
 * @param {string} sessionId
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeletePortForwardForSession(sessionId, id) {
    return $Call.ByID(2774978866, sessionId, id);
}

/**
 * @param {string} fileName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProgramFont(fileName) {
    return $Call.ByID(2577571490, fileName);
}

/**
 * @param {string} themeID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteThemePackage(themeID) {
    return $Call.ByID(2157415258, themeID);
}

/**
 * DisconnectSSH closes an SSH connection
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectSSH(sessionId) {
    return $Call.ByID(2542387286, sessionId);
}

/**
 * DoQuit 用户确认退出，设标记让 OnBeforeClose 放行
 * 同时清理资源：断开所有 SSH 会话、关闭 WebSocket 监听器
 * @returns {$CancellablePromise<void>}
 */
export function DoQuit() {
    return $Call.ByID(2702556168);
}

/**
 * @param {string} sessionId
 * @param {string} downloadID
 * @param {string} remotePath
 * @param {string} localDir
 * @param {string} optionsJSON
 * @returns {$CancellablePromise<void>}
 */
export function DownloadDirectoryCompressed(sessionId, downloadID, remotePath, localDir, optionsJSON) {
    return $Call.ByID(2730013248, sessionId, downloadID, remotePath, localDir, optionsJSON);
}

/**
 * @param {string} sessionId
 * @param {string} downloadID
 * @param {string} remotePath
 * @param {string} localDir
 * @param {string} optionsJSON
 * @returns {$CancellablePromise<void>}
 */
export function DownloadDirectoryToLocal(sessionId, downloadID, remotePath, localDir, optionsJSON) {
    return $Call.ByID(1734486691, sessionId, downloadID, remotePath, localDir, optionsJSON);
}

/**
 * @param {string} sessionId
 * @param {string} remotePath
 * @param {string} defaultDir
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFile(sessionId, remotePath, defaultDir) {
    return $Call.ByID(1034026940, sessionId, remotePath, defaultDir);
}

/**
 * @param {string} sessionId
 * @param {string} downloadID
 * @param {string} remotePath
 * @param {string} localPath
 * @param {string} optionsJSON
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFileToLocal(sessionId, downloadID, remotePath, localPath, optionsJSON) {
    return $Call.ByID(2849125432, sessionId, downloadID, remotePath, localPath, optionsJSON);
}

/**
 * DownloadImportTemplate 下载导入模板（含样例的明文 JSON），方便用户批量录入。
 * 弹出保存对话框；用户取消时返回 ("", nil)。返回写入的文件路径。
 * @param {string} lang
 * @returns {$CancellablePromise<string>}
 */
export function DownloadImportTemplate(lang) {
    return $Call.ByID(3292173669, lang);
}

/**
 * EnsureRemoteDirAndRetrySync 先重建远端同步目录再重试同步（目录 404/被删时使用）
 * @returns {$CancellablePromise<string>}
 */
export function EnsureRemoteDirAndRetrySync() {
    return $Call.ByID(2606109467);
}

/**
 * ExportConnections 导出全部节点到用户选择的文件。
 * useEncryption=false 导出明文 .json（含真实密码/私钥）；true 导出密文 .lumin2。
 * password 非空时用于 LUMIN2 PBKDF2 派生；空则用本机恢复密码（与云端同步加密口径一致）。
 * 弹出保存对话框；用户取消时返回 ("", nil)。返回写入的文件路径。
 * @param {boolean} useEncryption
 * @param {string} password
 * @returns {$CancellablePromise<string>}
 */
export function ExportConnections(useEncryption, password) {
    return $Call.ByID(2007392489, useEncryption, password);
}

/**
 * ExportConnectionsByIDs 按 ID 列表导出节点到用户选择的文件。
 * ids 为空时等同导出全部（向后兼容 ExportConnections）。
 * useEncryption=false 导出明文 .json；true 导出密文 .lumin2。
 * password 非空时用于 LUMIN2 PBKDF2 派生；空则用本机恢复密码。
 * @param {string[]} ids
 * @param {boolean} useEncryption
 * @param {string} password
 * @returns {$CancellablePromise<string>}
 */
export function ExportConnectionsByIDs(ids, useEncryption, password) {
    return $Call.ByID(1686241602, ids, useEncryption, password);
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function FinishChunkedUploadTask(taskID) {
    return $Call.ByID(2183797419, taskID);
}

/**
 * GetArch returns the current executable's CPU architecture (amd64, arm64, etc.)
 * @returns {$CancellablePromise<string>}
 */
export function GetArch() {
    return $Call.ByID(1785029150);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoSyncEnabled() {
    return $Call.ByID(3222957379);
}

/**
 * @param {string} providerID
 * @returns {$CancellablePromise<$models.BuiltinProviderRuntimeStatus>}
 */
export function GetBuiltinProviderRuntimeStatus(providerID) {
    return $Call.ByID(4150368374, providerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetChmodDialogSettings returns remembered chmod dialog preferences
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetChmodDialogSettings() {
    return $Call.ByID(11069810).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCommandHistory 获取指定会话的命令历史
 * @param {string} sessionId
 * @returns {$CancellablePromise<string>}
 */
export function GetCommandHistory(sessionId) {
    return $Call.ByID(947190905, sessionId);
}

/**
 * GetConnectionByID 返回指定连接的真实数据（含解密密码），供克隆等场景使用
 * @param {string} id
 * @returns {$CancellablePromise<config$0.Connection>}
 */
export function GetConnectionByID(id) {
    return $Call.ByID(2378353846, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetConnectionPassword(id) {
    return $Call.ByID(3958436879, id);
}

/**
 * GetConnections returns all saved SSH connections
 * @returns {$CancellablePromise<config$0.Connection[]>}
 */
export function GetConnections() {
    return $Call.ByID(2023234531).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetConnectionsMasked 返回掩码后的连接列表，用于前端显示
 * @returns {$CancellablePromise<config$0.Connection[]>}
 */
export function GetConnectionsMasked() {
    return $Call.ByID(82682326).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Credential[]>}
 */
export function GetCredentials() {
    return $Call.ByID(1518090272).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * FTP Methods
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetFTPConfig() {
    return $Call.ByID(535308130).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetFileManagerSettings() {
    return $Call.ByID(3172198354).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetFullProcessList retrieves all process list from the remote server
 * @param {string} sessionId
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetFullProcessList(sessionId) {
    return $Call.ByID(1636267236, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GitHubContributor[]>}
 */
export function GetGitHubContributors() {
    return $Call.ByID(27980187).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetGlobalCommandHistory 获取全局命令历史
 * @returns {$CancellablePromise<string>}
 */
export function GetGlobalCommandHistory() {
    return $Call.ByID(2561969638);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetLastSyncTime() {
    return $Call.ByID(3237123960);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLiveWorkspaceState() {
    return $Call.ByID(2796702354);
}

/**
 * GetLocalShells lists detected shells on the local system.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLocalShells() {
    return $Call.ByID(367135694).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetMCPOutputCompressionSettings() {
    return $Call.ByID(969208158).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetMCPServerInfo() {
    return $Call.ByID(2497598693).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetMCPSettingsState() {
    return $Call.ByID(492493272).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetParamHistory 获取参数历史
 * @returns {$CancellablePromise<string>}
 */
export function GetParamHistory() {
    return $Call.ByID(1932895769);
}

/**
 * @param {string} sessionId
 * @param {string} path
 * @returns {$CancellablePromise<sshmanager$0.PathOwnershipInfo>}
 */
export function GetPathOwnership(sessionId, path) {
    return $Call.ByID(530600438, sessionId, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetProcessEnv returns environment variables of a remote process
 * @param {string} sessionId
 * @param {string} pid
 * @returns {$CancellablePromise<string[]>}
 */
export function GetProcessEnv(sessionId, pid) {
    return $Call.ByID(1362176638, sessionId, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetProgramDirectory() {
    return $Call.ByID(3967616477);
}

/**
 * @param {string} fileName
 * @returns {$CancellablePromise<string>}
 */
export function GetProgramFontDataURL(fileName) {
    return $Call.ByID(2015721848, fileName);
}

/**
 * @returns {$CancellablePromise<ai$0.AIProxyNode[]>}
 */
export function GetProxyNodes() {
    return $Call.ByID(253472919).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetQuickCommands 获取快捷命令列表
 * @returns {$CancellablePromise<string>}
 */
export function GetQuickCommands() {
    return $Call.ByID(3833421103);
}

/**
 * R2 Methods
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetR2Config() {
    return $Call.ByID(3498228708).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RecoveryPassword methods
 * @returns {$CancellablePromise<string>}
 */
export function GetRecoveryPassword() {
    return $Call.ByID(1128293116);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetRememberWorkspace() {
    return $Call.ByID(940642026);
}

/**
 * @returns {$CancellablePromise<runtimeenv$0.Settings>}
 */
export function GetRuntimeEnvironmentSettings() {
    return $Call.ByID(1591717862).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<runtimeenv$0.Status>}
 */
export function GetRuntimeEnvironmentStatus() {
    return $Call.ByID(3309706445).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * SFTP Methods
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSFTPConfig() {
    return $Call.ByID(4224700741).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSSHChannelUsage 返回当前会话占用的 SSH 通道数量明细
 * @param {string} sessionId
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSSHChannelUsage(sessionId) {
    return $Call.ByID(3932401926, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetServerStaticInfo retrieves static server info (OS/timezone/hostname/CPU model)
 * @param {string} sessionId
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetServerStaticInfo(sessionId) {
    return $Call.ByID(559774467, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SyncMode methods
 * @returns {$CancellablePromise<string>}
 */
export function GetSyncMode() {
    return $Call.ByID(2443347538);
}

/**
 * GetSyncTombstoneStats 返回本地同步删除记录条数。
 * @returns {$CancellablePromise<config$0.SyncTombstoneStats>}
 */
export function GetSyncTombstoneStats() {
    return $Call.ByID(545653771).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetTasksDir 返回当前 AI 对话存储目录（自定义路径或默认 configDir/tasks）
 * @returns {$CancellablePromise<string>}
 */
export function GetTasksDir() {
    return $Call.ByID(2540294255);
}

/**
 * GetTerminalCwd retrieves current working directory of the shell
 * @param {string} sessionId
 * @returns {$CancellablePromise<string>}
 */
export function GetTerminalCwd(sessionId) {
    return $Call.ByID(3923409300, sessionId);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetThemePackageSettings() {
    return $Call.ByID(1850639192).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetThemePackagesDirectory() {
    return $Call.ByID(4118609265);
}

/**
 * WebDAV Methods
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetWebdavConfig() {
    return $Call.ByID(1909966529).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetWebviewGpuDisabled() {
    return $Call.ByID(95181289);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkspacePersistenceLevel() {
    return $Call.ByID(3809246760);
}

/**
 * @param {string} serverId
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkspaceSessionState(serverId) {
    return $Call.ByID(2684021986, serverId);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkspaceState() {
    return $Call.ByID(1207541832);
}

/**
 * GetWsPort 返回本地 WebSocket 服务器端口，前端用于连接终端
 * @returns {$CancellablePromise<number>}
 */
export function GetWsPort() {
    return $Call.ByID(797700107);
}

/**
 * GetWsToken 返回 WebSocket 鉴权 token，前端连接时通过 ?token=xxx 携带
 * @returns {$CancellablePromise<string>}
 */
export function GetWsToken() {
    return $Call.ByID(2049520773);
}

/**
 * @param {ai$0.ThemeToolRequest} request
 * @returns {$CancellablePromise<ai$0.ThemeToolResult>}
 */
export function HandleThemeToolRequest(request) {
    return $Call.ByID(1688173340, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * HasRecoveryPassword 返回是否设置了恢复密码（供前端导出 UI 决定是否允许"复用恢复密码"）。
 * @returns {$CancellablePromise<boolean>}
 */
export function HasRecoveryPassword() {
    return $Call.ByID(4117414368);
}

/**
 * ImportConnections 从指定文件导入节点（合并，跳过重复）。
 * filePath 由前端通过 SelectImportFile 获取；password 为弹窗输入的自定义解密密码（可空）。
 * 智能识别明文 JSON / LUMIN2 密文：
 *   - 明文直接解析
 *   - 密文优先用本机恢复密码，失败返回 config.ErrNeedPassword，前端弹窗输入自定义密码后再试
 * @param {string} filePath
 * @param {string} password
 * @returns {$CancellablePromise<config$0.ImportResult>}
 */
export function ImportConnections(filePath, password) {
    return $Call.ByID(3572667828, filePath, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<programfonts$0.ProgramFontInfo[]>}
 */
export function ImportProgramFontFiles(paths) {
    return $Call.ByID(2204288083, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ImportThemePackageFiles(paths) {
    return $Call.ByID(1035508567, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} providerID
 * @param {string} language
 * @returns {$CancellablePromise<void>}
 */
export function InitializeBuiltinProvider(providerID, language) {
    return $Call.ByID(3782074542, providerID, language);
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function InjectAIBuiltinLoginBridge(jsonStr) {
    return $Call.ByID(327325396, jsonStr);
}

/**
 * @param {string} language
 * @returns {$CancellablePromise<runtimeenv$0.Status>}
 */
export function InstallRuntimeEnvironment(language) {
    return $Call.ByID(4022186264, language).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function InstallUnzip(sessionId) {
    return $Call.ByID(3077099789, sessionId);
}

/**
 * IsCustomTasksDir 返回是否使用了自定义 AI 对话存储目录
 * @returns {$CancellablePromise<boolean>}
 */
export function IsCustomTasksDir() {
    return $Call.ByID(562811596);
}

/**
 * IsPortableVersion checks if the current executable is the portable version
 * 开发构建默认视为便携版（exe 名不含 installer/setup）
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPortableVersion() {
    return $Call.ByID(4209125875);
}

/**
 * KillProcess kills a process by PID on the remote server
 * @param {string} sessionId
 * @param {string} pid
 * @returns {$CancellablePromise<void>}
 */
export function KillProcess(sessionId, pid) {
    return $Call.ByID(1028100019, sessionId, pid);
}

/**
 * @returns {$CancellablePromise<mcpserver$0.ConnectedSession[]>}
 */
export function ListConnectedSessions() {
    return $Call.ByID(722769644).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ListDir lists directory contents via SFTP
 * @param {string} sessionId
 * @param {string} path
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListDir(sessionId, path) {
    return $Call.ByID(2865888157, sessionId, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListExternalEditSessions returns active external-edit sessions.
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListExternalEditSessions() {
    return $Call.ByID(2717484640).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListFTPBackups() {
    return $Call.ByID(2422362603).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} sessionId
 * @returns {$CancellablePromise<sshmanager$0.OwnershipCandidates>}
 */
export function ListOwnershipCandidates(sessionId) {
    return $Call.ByID(1066640069, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {string} sessionId
 * @returns {$CancellablePromise<sshmanager$0.PortForwardInfo[]>}
 */
export function ListPortForwards(sessionId) {
    return $Call.ByID(3653317367, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @returns {$CancellablePromise<programfonts$0.ProgramFontInfo[]>}
 */
export function ListProgramFonts() {
    return $Call.ByID(1325049612).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListR2Backups() {
    return $Call.ByID(862490013).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListSFTPBackups() {
    return $Call.ByID(1660306282).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListSerialPorts returns the list of available serial port names.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSerialPorts() {
    return $Call.ByID(3037638402).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListThemePackages() {
    return $Call.ByID(3926887122).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListWebdavBackups() {
    return $Call.ByID(112562278).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<void>}
 */
export function MarkThemeToolConversationUserConfirmed(conversationID) {
    return $Call.ByID(1675765635, conversationID);
}

/**
 * MigrateAITasksDir 将 AI 对话数据迁移到目标目录
 * @param {string} targetDir
 * @returns {$CancellablePromise<void>}
 */
export function MigrateAITasksDir(targetDir) {
    return $Call.ByID(3039892780, targetDir);
}

/**
 * Mkdir creates a directory via SFTP
 * @param {string} sessionId
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(sessionId, path) {
    return $Call.ByID(2443009777, sessionId, path);
}

/**
 * MoveItem moves a file or directory within the same server (server-local mv).
 * @param {string} sessionId
 * @param {string} srcPath
 * @param {string} dstPath
 * @returns {$CancellablePromise<void>}
 */
export function MoveItem(sessionId, srcPath, dstPath) {
    return $Call.ByID(546179552, sessionId, srcPath, dstPath);
}

/**
 * NetworkInfo retrieves full network probe info including connection details.
 * @param {string} sessionId
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function NetworkInfo(sessionId) {
    return $Call.ByID(2062959444, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} providerID
 * @returns {$CancellablePromise<void>}
 */
export function OpenBuiltinProviderDoc(providerID) {
    return $Call.ByID(1255437298, providerID);
}

/**
 * @param {string} localPath
 * @param {boolean} isDirectory
 * @returns {$CancellablePromise<void>}
 */
export function OpenLocalPathInExplorer(localPath, isDirectory) {
    return $Call.ByID(2595909938, localPath, isDirectory);
}

/**
 * OpenRemoteFileInSystemEditor downloads a remote file to a local temp path and opens it
 * with the OS default application. When readOnly is false, local changes are watched and
 * synced back via SFTP; when true (e.g. media files opened for viewing), no watch/sync is set up.
 * content may be empty to re-read from remote; non-empty content is used as the initial temp file.
 * 编辑大小上限由用户配置（GetFileManagerMaxEditSizeBytes），每次打开实时读取以反映最新设置。
 * @param {string} sessionId
 * @param {string} remotePath
 * @param {string} content
 * @param {boolean} readOnly
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function OpenRemoteFileInSystemEditor(sessionId, remotePath, content, readOnly) {
    return $Call.ByID(2846417337, sessionId, remotePath, content, readOnly).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenRemoteFileWithEditor is like OpenRemoteFileInSystemEditor but launches a specific editor binary/.app.
 * @param {string} sessionId
 * @param {string} remotePath
 * @param {string} content
 * @param {string} editorPath
 * @param {boolean} readOnly
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function OpenRemoteFileWithEditor(sessionId, remotePath, content, editorPath, readOnly) {
    return $Call.ByID(1468960267, sessionId, remotePath, content, editorPath, readOnly).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenTerminal 在当前服务器连接上打开新的终端标签页
 * @param {string} sessionId
 * @returns {$CancellablePromise<string>}
 */
export function OpenTerminal(sessionId) {
    return $Call.ByID(3910325546, sessionId);
}

/**
 * PingServer pings a server. mode 为延迟检测方式：auto / banner / tcp（见 ping.go normalizePingMode）。
 * @param {string} connId
 * @param {string} mode
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function PingServer(connId, mode) {
    return $Call.ByID(3099417653, connId, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} sessionId
 * @param {string} remotePath
 * @param {string} localPath
 * @param {boolean} isDirectory
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function PreviewDownloadConflicts(sessionId, remotePath, localPath, isDirectory) {
    return $Call.ByID(4210230469, sessionId, remotePath, localPath, isDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * PreviewSmartUncompressItem previews smart extract destination without modifying files.
 * @param {string} sessionId
 * @param {string} remotePath
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function PreviewSmartUncompressItem(sessionId, remotePath) {
    return $Call.ByID(3475309527, sessionId, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PreviewTombstoneConflicts 合并同步前：先读目标云，列出本地墓碑将删掉的远端项。
 * @returns {$CancellablePromise<config$0.TombstoneConflictPreview>}
 */
export function PreviewTombstoneConflicts() {
    return $Call.ByID(574209876).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * PruneSyncTombstones 按天数清理删除记录并上传到已配置云端。
 * days <= 0 表示清理全部。
 * @param {number} days
 * @returns {$CancellablePromise<config$0.SyncTombstonePruneResult>}
 */
export function PruneSyncTombstones(days) {
    return $Call.ByID(547393985, days).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * ReadFile reads a file's content via SFTP
 * @param {string} sessionId
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(sessionId, path) {
    return $Call.ByID(3933599540, sessionId, path);
}

/**
 * ReadPrivateKeyFile opens a file dialog to read a private key file
 * @returns {$CancellablePromise<string>}
 */
export function ReadPrivateKeyFile() {
    return $Call.ByID(3531544814);
}

/**
 * ReconnectWithPassword 更新密码并重连（认证失败后使用）
 * persist: true=保存密码, false=仅本次会话使用
 * @param {string} sessionId
 * @param {string} connId
 * @param {string} newPassword
 * @param {boolean} persist
 * @returns {$CancellablePromise<void>}
 */
export function ReconnectWithPassword(sessionId, connId, newPassword, persist) {
    return $Call.ByID(2473454546, sessionId, connId, newPassword, persist);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReloadMCPGlobalServers() {
    return $Call.ByID(495456358);
}

/**
 * RenameConnectionGroup 重命名服务器分组（批量更新该组下所有连接的 group）
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameConnectionGroup(oldName, newName) {
    return $Call.ByID(3228126999, oldName, newName);
}

/**
 * RenameItem renames a file or directory via SFTP
 * @param {string} sessionId
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameItem(sessionId, oldPath, newPath) {
    return $Call.ByID(2632658987, sessionId, oldPath, newPath);
}

/**
 * @param {string} newPassword
 * @returns {$CancellablePromise<void>}
 */
export function ResetRecoveryPassword(newPassword) {
    return $Call.ByID(108608371, newPassword);
}

/**
 * ResetTasksDir 重置为默认目录（迁移数据后清除自定义路径设置）
 * @returns {$CancellablePromise<void>}
 */
export function ResetTasksDir() {
    return $Call.ByID(648834052);
}

/**
 * ResizeTerminal resizes the SSH PTY
 * @param {string} sessionId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(sessionId, cols, rows) {
    return $Call.ByID(500558094, sessionId, cols, rows);
}

/**
 * @param {string} sessionId
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ResolveDirectoryPath(sessionId, path) {
    return $Call.ByID(2644166690, sessionId, path);
}

/**
 * @param {string} localPath
 * @param {boolean} isDirectory
 * @param {string} optionsJSON
 * @returns {$CancellablePromise<string>}
 */
export function ResolveDownloadLocalPath(localPath, isDirectory, optionsJSON) {
    return $Call.ByID(1620265082, localPath, isDirectory, optionsJSON);
}

/**
 * @param {string} remotePath
 * @param {string} defaultDir
 * @param {boolean} isDirectory
 * @param {string} optionsJSON
 * @returns {$CancellablePromise<string>}
 */
export function ResolveDownloadPath(remotePath, defaultDir, isDirectory, optionsJSON) {
    return $Call.ByID(394995321, remotePath, defaultDir, isDirectory, optionsJSON);
}

/**
 * @param {string} name
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function RestartMCPClientServer(name, source) {
    return $Call.ByID(2824179743, name, source);
}

/**
 * @param {string} sessionId
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function RestartPortForwardForSession(sessionId, id) {
    return $Call.ByID(4191538858, sessionId, id);
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromFTPFile(filename) {
    return $Call.ByID(1165431520, filename).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filename
 * @param {string} password
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromFTPFileWithPassword(filename, password) {
    return $Call.ByID(705364113, filename, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} objectKey
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromR2File(objectKey) {
    return $Call.ByID(855161786, objectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} objectKey
 * @param {string} password
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromR2FileWithPassword(objectKey, password) {
    return $Call.ByID(374279579, objectKey, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromSFTPFile(filename) {
    return $Call.ByID(3890392359, filename).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filename
 * @param {string} password
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromSFTPFileWithPassword(filename, password) {
    return $Call.ByID(2233542150, filename, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromWebdavFile(filename) {
    return $Call.ByID(3248670751, filename).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filename
 * @param {string} password
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function RestoreFromWebdavFileWithPassword(filename, password) {
    return $Call.ByID(728473646, filename, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RetrySync 手动重试云端同步，返回空字符串表示成功，非空为错误信息
 * @returns {$CancellablePromise<string>}
 */
export function RetrySync() {
    return $Call.ByID(779514259);
}

/**
 * SaveChmodDialogSettings persists chmod dialog preferences
 * @param {string} mode
 * @param {boolean} includeSubdirectories
 * @returns {$CancellablePromise<void>}
 */
export function SaveChmodDialogSettings(mode, includeSubdirectories) {
    return $Call.ByID(3089932029, mode, includeSubdirectories);
}

/**
 * SaveCommandHistory 保存指定会话的命令历史
 * @param {string} sessionId
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveCommandHistory(sessionId, jsonStr) {
    return $Call.ByID(2228127748, sessionId, jsonStr);
}

/**
 * SaveConnection saves a new or existing connection
 * @param {config$0.Connection} conn
 * @param {boolean} noSync
 * @returns {$CancellablePromise<config$0.Connection>}
 */
export function SaveConnection(conn, noSync) {
    return $Call.ByID(1206341423, conn, noSync).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {config$0.Credential} cred
 * @returns {$CancellablePromise<config$0.Credential>}
 */
export function SaveCredential(cred) {
    return $Call.ByID(1134746622, cred).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {{ [_ in string]?: string }} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveFTPConfig(config) {
    return $Call.ByID(2253210029, config);
}

/**
 * SaveGlobalCommandHistory 保存全局命令历史
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveGlobalCommandHistory(jsonStr) {
    return $Call.ByID(3639242783, jsonStr);
}

/**
 * @param {string} name
 * @param {string} configText
 * @returns {$CancellablePromise<void>}
 */
export function SaveMCPGlobalServer(name, configText) {
    return $Call.ByID(1329555497, name, configText);
}

/**
 * @param {number} lineLimit
 * @param {number} characterLimit
 * @returns {$CancellablePromise<void>}
 */
export function SaveMCPOutputCompressionSettings(lineLimit, characterLimit) {
    return $Call.ByID(3187496619, lineLimit, characterLimit);
}

/**
 * SaveParamHistory 保存参数历史
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveParamHistory(jsonStr) {
    return $Call.ByID(2935278052, jsonStr);
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveProxyNodes(jsonStr) {
    return $Call.ByID(3607231310, jsonStr);
}

/**
 * SaveQuickCommands 保存快捷命令列表
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveQuickCommands(jsonStr) {
    return $Call.ByID(3122703640, jsonStr);
}

/**
 * SaveQuickCommandsLocal 保存快捷命令列表到本地，不触发云端同步
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveQuickCommandsLocal(jsonStr) {
    return $Call.ByID(3918358515, jsonStr);
}

/**
 * @param {{ [_ in string]?: string }} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveR2Config(config) {
    return $Call.ByID(1291948021, config);
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveRuntimeEnvironmentSettings(jsonStr) {
    return $Call.ByID(1657294923, jsonStr);
}

/**
 * @param {{ [_ in string]?: string }} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveSFTPConfig(config) {
    return $Call.ByID(301649028, config);
}

/**
 * @param {{ [_ in string]?: string }} payload
 * @returns {$CancellablePromise<void>}
 */
export function SaveThemePackageSettings(payload) {
    return $Call.ByID(2788334325, payload);
}

/**
 * @param {number} maxPacketKiB
 * @param {number} maxRequestsPerFile
 * @param {boolean} concurrentWrites
 * @param {boolean} applyToSharedClient
 * @returns {$CancellablePromise<void>}
 */
export function SaveTransferTuningSettings(maxPacketKiB, maxRequestsPerFile, concurrentWrites, applyToSharedClient) {
    return $Call.ByID(3921232688, maxPacketKiB, maxRequestsPerFile, concurrentWrites, applyToSharedClient);
}

/**
 * @param {{ [_ in string]?: string }} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveWebdavConfig(config) {
    return $Call.ByID(2941915412, config);
}

/**
 * @param {string} serverId
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkspaceSessionState(serverId, jsonStr) {
    return $Call.ByID(2530315949, serverId, jsonStr);
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkspaceState(jsonStr) {
    return $Call.ByID(3128304305, jsonStr);
}

/**
 * @param {string} defaultDir
 * @returns {$CancellablePromise<string>}
 */
export function SelectDownloadDirectory(defaultDir) {
    return $Call.ByID(1051442913, defaultDir);
}

/**
 * @param {string} remotePath
 * @param {string} defaultDir
 * @returns {$CancellablePromise<string>}
 */
export function SelectDownloadFilePath(remotePath, defaultDir) {
    return $Call.ByID(602653043, remotePath, defaultDir);
}

/**
 * SelectExternalEditor opens a native file dialog for choosing an editor executable.
 * @returns {$CancellablePromise<string>}
 */
export function SelectExternalEditor() {
    return $Call.ByID(2685460588);
}

/**
 * SelectImportFile 弹出打开对话框让用户选择导入文件，返回文件路径（用户取消返回空串）。
 * 与 ImportConnections 分离，便于密文导入需要密码时无需重新选文件。
 * @returns {$CancellablePromise<string>}
 */
export function SelectImportFile() {
    return $Call.ByID(481735137);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectProgramFontFiles() {
    return $Call.ByID(3040208714).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SelectTasksDirectory 弹出目录选择对话框，返回用户选择的目录路径
 * @returns {$CancellablePromise<string>}
 */
export function SelectTasksDirectory() {
    return $Call.ByID(1627624943);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectThemePackageFiles() {
    return $Call.ByID(1437301244).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectUploadDirectory() {
    return $Call.ByID(1655130686);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectUploadFiles() {
    return $Call.ByID(3991179294).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoSyncEnabled(enabled) {
    return $Call.ByID(1012026679, enabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetChmodAutoApplyLastSettings(enabled) {
    return $Call.ByID(941008965, enabled);
}

/**
 * SetConnectionGroup 仅更新服务器分组
 * @param {string} id
 * @param {string} group
 * @returns {$CancellablePromise<void>}
 */
export function SetConnectionGroup(id, group) {
    return $Call.ByID(286613473, id, group);
}

/**
 * SetConnectionOS 仅更新服务器操作系统
 * @param {string} id
 * @param {string} os
 * @returns {$CancellablePromise<void>}
 */
export function SetConnectionOS(id, os) {
    return $Call.ByID(891877312, id, os);
}

/**
 * @param {boolean} disabled
 * @returns {$CancellablePromise<void>}
 */
export function SetFileManagerAutoRefreshDisabled(disabled) {
    return $Call.ByID(1136504515, disabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetFileManagerDoubleClickUncompressArchive(enabled) {
    return $Call.ByID(3737548069, enabled);
}

/**
 * SetFileManagerMaxEditSize sets the max editable file size (MB), normalized to [1, 50].
 * @param {number} mb
 * @returns {$CancellablePromise<void>}
 */
export function SetFileManagerMaxEditSize(mb) {
    return $Call.ByID(1864437822, mb);
}

/**
 * @param {string} strategy
 * @returns {$CancellablePromise<void>}
 */
export function SetFileManagerSmartUncompressConflictStrategy(strategy) {
    return $Call.ByID(4046119760, strategy);
}

/**
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SetLiveWorkspaceState(jsonStr) {
    return $Call.ByID(2641948526, jsonStr);
}

/**
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function SetRecoveryPassword(password) {
    return $Call.ByID(1398381112, password);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetRememberWorkspace(enabled) {
    return $Call.ByID(211754374, enabled);
}

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetSyncMode(mode) {
    return $Call.ByID(3708397342, mode);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetWebviewGpuDisabled(enabled) {
    return $Call.ByID(1172353317, enabled);
}

/**
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkspacePersistenceLevel(level) {
    return $Call.ByID(394638300, level);
}

/**
 * @param {string} sessionId
 * @param {string} localAddr
 * @param {string} remoteAddr
 * @returns {$CancellablePromise<string>}
 */
export function StartLocalPortForward(sessionId, localAddr, remoteAddr) {
    return $Call.ByID(833105367, sessionId, localAddr, remoteAddr);
}

/**
 * @param {string} sessionId
 * @param {string} remoteAddr
 * @param {string} localAddr
 * @returns {$CancellablePromise<string>}
 */
export function StartRemotePortForward(sessionId, remoteAddr, localAddr) {
    return $Call.ByID(2576183736, sessionId, remoteAddr, localAddr);
}

/**
 * StopExternalEdit stops watching and cleans temp files for one remote path.
 * @param {string} sessionId
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function StopExternalEdit(sessionId, remotePath) {
    return $Call.ByID(2469336989, sessionId, remotePath);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopPortForward(id) {
    return $Call.ByID(1481034258, id);
}

/**
 * @param {string} sessionId
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopPortForwardForSession(sessionId, id) {
    return $Call.ByID(2781984995, sessionId, id);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function SupportsWebviewGpuDisable() {
    return $Call.ByID(2889122655);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SyncAllProviders() {
    return $Call.ByID(507566738).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SyncFromFTP() {
    return $Call.ByID(4216821905).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SyncFromR2() {
    return $Call.ByID(1035597849).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SyncFromSFTP() {
    return $Call.ByID(1359692140).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SyncFromWebdav() {
    return $Call.ByID(2005443704).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} password
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SyncWithRecoveryPassword(password) {
    return $Call.ByID(290738923, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SystemInfo retrieves basic system probe info
 * @param {string} sessionId
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SystemInfo(sessionId) {
    return $Call.ByID(4086640583, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} host
 * @param {number} port
 * @param {string} username
 * @param {string} password
 * @param {string} mode
 * @returns {$CancellablePromise<config$0.FTPConnectionTestResult | null>}
 */
export function TestFTPConnection(host, port, username, password, mode) {
    return $Call.ByID(3384754904, host, port, username, password, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {string} host
 * @param {number} port
 * @param {string} username
 * @param {string} password
 * @param {string} mode
 * @param {string} approvedFingerprint
 * @param {string} expectedPinnedFingerprint
 * @returns {$CancellablePromise<config$0.FTPConnectionTestResult | null>}
 */
export function TestFTPConnectionWithCertificateApproval(host, port, username, password, mode, approvedFingerprint, expectedPinnedFingerprint) {
    return $Call.ByID(2238313188, host, port, username, password, mode, approvedFingerprint, expectedPinnedFingerprint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {string} accessKeyId
 * @param {string} secretAccessKey
 * @param {string} bucket
 * @param {string} endpoint
 * @returns {$CancellablePromise<void>}
 */
export function TestR2Connection(accessKeyId, secretAccessKey, bucket, endpoint) {
    return $Call.ByID(1609270826, accessKeyId, secretAccessKey, bucket, endpoint);
}

/**
 * @param {string} host
 * @param {number} port
 * @param {string} username
 * @param {string} password
 * @param {string} authMethod
 * @param {string} privateKey
 * @param {string} passphrase
 * @returns {$CancellablePromise<config$0.SFTPConnectionTestResult | null>}
 */
export function TestSFTPConnection(host, port, username, password, authMethod, privateKey, passphrase) {
    return $Call.ByID(1992077227, host, port, username, password, authMethod, privateKey, passphrase).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @param {string} host
 * @param {number} port
 * @param {string} username
 * @param {string} password
 * @param {string} authMethod
 * @param {string} privateKey
 * @param {string} passphrase
 * @param {string} approvedFingerprint
 * @returns {$CancellablePromise<config$0.SFTPConnectionTestResult | null>}
 */
export function TestSFTPConnectionWithHostKeyApproval(host, port, username, password, authMethod, privateKey, passphrase, approvedFingerprint) {
    return $Call.ByID(3880781967, host, port, username, password, authMethod, privateKey, passphrase, approvedFingerprint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @param {string} url
 * @param {string} username
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function TestWebdavConnection(url, username, password) {
    return $Call.ByID(3026087087, url, username, password);
}

/**
 * @param {string} name
 * @param {string} source
 * @param {boolean} disabled
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMCPClientServer(name, source, disabled) {
    return $Call.ByID(2457613194, name, source, disabled);
}

/**
 * @param {string} name
 * @param {string} source
 * @param {boolean} disabledForPrompts
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMCPClientServerDisabledForPrompts(name, source, disabledForPrompts) {
    return $Call.ByID(793752676, name, source, disabledForPrompts);
}

/**
 * UncompressItem extracts an archive on the remote server using the saved smart extract strategy.
 * @param {string} sessionId
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UncompressItem(sessionId, remotePath) {
    return $Call.ByID(488432898, sessionId, remotePath);
}

/**
 * UncompressItemWithStrategy extracts an archive on the remote server using a caller-provided conflict strategy.
 * @param {string} sessionId
 * @param {string} remotePath
 * @param {string} strategy
 * @returns {$CancellablePromise<void>}
 */
export function UncompressItemWithStrategy(sessionId, remotePath, strategy) {
    return $Call.ByID(2457271031, sessionId, remotePath, strategy);
}

/**
 * UpdateApp downloads a platform update package, verifies it, and starts the
 * platform-specific installation or executable replacement flow.
 * @param {string} downloadUrl
 * @param {string} filename
 * @param {boolean} proxyFirst
 * @returns {$CancellablePromise<void>}
 */
export function UpdateApp(downloadUrl, filename, proxyFirst) {
    return $Call.ByID(2897282294, downloadUrl, filename, proxyFirst);
}

/**
 * @param {string} name
 * @param {string} source
 * @param {number} timeout
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMCPClientServerTimeout(name, source, timeout) {
    return $Call.ByID(554492160, name, source, timeout);
}

/**
 * @param {string} taskID
 * @param {string} fileID
 * @param {number} chunkIndex
 * @param {number} offset
 * @param {string} base64Content
 * @returns {$CancellablePromise<void>}
 */
export function UploadChunkBase64(taskID, fileID, chunkIndex, offset, base64Content) {
    return $Call.ByID(3836195427, taskID, fileID, chunkIndex, offset, base64Content);
}

/**
 * UploadFile opens a file dialog to select a local file and uploads it to the remote path
 * @param {string} sessionId
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(sessionId, remotePath) {
    return $Call.ByID(1540257073, sessionId, remotePath);
}

/**
 * UploadFileContent uploads file content from memory to a remote path
 * @param {string} sessionId
 * @param {string} fileName
 * @param {string} remoteDir
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function UploadFileContent(sessionId, fileName, remoteDir, content) {
    return $Call.ByID(2820185238, sessionId, fileName, remoteDir, content);
}

/**
 * UploadFileContentBase64 通过 base64 编码上传文件内容，避免前端内存爆炸
 * @param {string} sessionId
 * @param {string} fileName
 * @param {string} remoteDir
 * @param {string} base64Content
 * @returns {$CancellablePromise<void>}
 */
export function UploadFileContentBase64(sessionId, fileName, remoteDir, base64Content) {
    return $Call.ByID(2211593241, sessionId, fileName, remoteDir, base64Content);
}

/**
 * UploadLocalDir recursively uploads a local directory to a remote directory (no dialog)
 * @param {string} sessionId
 * @param {string} localDir
 * @param {string} remoteDir
 * @returns {$CancellablePromise<void>}
 */
export function UploadLocalDir(sessionId, localDir, remoteDir) {
    return $Call.ByID(1058105269, sessionId, localDir, remoteDir);
}

/**
 * UploadLocalFile uploads a local file to a remote directory (no dialog)
 * @param {string} sessionId
 * @param {string} localFile
 * @param {string} remoteDir
 * @returns {$CancellablePromise<void>}
 */
export function UploadLocalFile(sessionId, localFile, remoteDir) {
    return $Call.ByID(3460988120, sessionId, localFile, remoteDir);
}

/**
 * @param {string} sessionId
 * @param {string} uploadID
 * @param {number} maxConcurrent
 * @param {string[]} localPaths
 * @param {string} remoteDir
 * @returns {$CancellablePromise<void>}
 */
export function UploadLocalPathsCompressed(sessionId, uploadID, maxConcurrent, localPaths, remoteDir) {
    return $Call.ByID(3440768099, sessionId, uploadID, maxConcurrent, localPaths, remoteDir);
}

/**
 * WriteFile writes content to a file via SFTP
 * @param {string} sessionId
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(sessionId, path, content) {
    return $Call.ByID(2478277235, sessionId, path, content);
}

/**
 * WriteTerminal sends input to the SSH PTY (fallback, primary path is WebSocket)
 * @param {string} sessionId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(sessionId, data) {
    return $Call.ByID(539451553, sessionId, data);
}

/**
 * WriteWsOutput 将 WebSocket 输出写入给指定 session 的 WS 连接
 * @param {string} sessionId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteWsOutput(sessionId, data) {
    return $Call.ByID(2087628642, sessionId, data);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.BuiltinProviderRuntimeStatus.createFrom;
const $$createType2 = config$0.Connection.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = config$0.Credential.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = $models.GitHubContributor.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = sshmanager$0.PathOwnershipInfo.createFrom;
const $$createType12 = ai$0.AIProxyNode.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = runtimeenv$0.Settings.createFrom;
const $$createType15 = runtimeenv$0.Status.createFrom;
const $$createType16 = config$0.SyncTombstoneStats.createFrom;
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = ai$0.ThemeToolResult.createFrom;
const $$createType19 = config$0.ImportResult.createFrom;
const $$createType20 = programfonts$0.ProgramFontInfo.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = mcpserver$0.ConnectedSession.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = sshmanager$0.OwnershipCandidates.createFrom;
const $$createType25 = sshmanager$0.PortForwardInfo.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = config$0.TombstoneConflictPreview.createFrom;
const $$createType28 = config$0.SyncTombstonePruneResult.createFrom;
const $$createType29 = config$0.FTPConnectionTestResult.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = config$0.SFTPConnectionTestResult.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
