// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BuiltinProviderRuntimeStatus {
    /**
     * Creates a new BuiltinProviderRuntimeStatus instance.
     * @param {Partial<BuiltinProviderRuntimeStatus>} [$$source = {}] - The source object to create the BuiltinProviderRuntimeStatus.
     */
    constructor($$source = {}) {
        if (!("providerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["providerId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuiltinProviderRuntimeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuiltinProviderRuntimeStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuiltinProviderRuntimeStatus(/** @type {Partial<BuiltinProviderRuntimeStatus>} */($$parsedSource));
    }
}

export class GitHubContributor {
    /**
     * Creates a new GitHubContributor instance.
     * @param {Partial<GitHubContributor>} [$$source = {}] - The source object to create the GitHubContributor.
     */
    constructor($$source = {}) {
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {GitHubContributorAuthor}
             */
            this["author"] = (new GitHubContributorAuthor());
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("weeks" in $$source)) {
            /**
             * @member
             * @type {GitHubContributorWeek[]}
             */
            this["weeks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubContributor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitHubContributor}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField0_0($$parsedSource["author"]);
        }
        if ("weeks" in $$parsedSource) {
            $$parsedSource["weeks"] = $$createField2_0($$parsedSource["weeks"]);
        }
        return new GitHubContributor(/** @type {Partial<GitHubContributor>} */($$parsedSource));
    }
}

export class GitHubContributorAuthor {
    /**
     * Creates a new GitHubContributorAuthor instance.
     * @param {Partial<GitHubContributorAuthor>} [$$source = {}] - The source object to create the GitHubContributorAuthor.
     */
    constructor($$source = {}) {
        if (!("login" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["login"] = "";
        }
        if (!("avatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubContributorAuthor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitHubContributorAuthor}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubContributorAuthor(/** @type {Partial<GitHubContributorAuthor>} */($$parsedSource));
    }
}

export class GitHubContributorWeek {
    /**
     * Creates a new GitHubContributorWeek instance.
     * @param {Partial<GitHubContributorWeek>} [$$source = {}] - The source object to create the GitHubContributorWeek.
     */
    constructor($$source = {}) {
        if (!("w" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["w"] = 0;
        }
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["a"] = 0;
        }
        if (!("d" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["d"] = 0;
        }
        if (!("c" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["c"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubContributorWeek instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitHubContributorWeek}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubContributorWeek(/** @type {Partial<GitHubContributorWeek>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GitHubContributorAuthor.createFrom;
const $$createType1 = GitHubContributorWeek.createFrom;
const $$createType2 = $Create.Array($$createType1);
