// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AIChatCommandTerminalCandidate {
    /**
     * Creates a new AIChatCommandTerminalCandidate instance.
     * @param {Partial<AIChatCommandTerminalCandidate>} [$$source = {}] - The source object to create the AIChatCommandTerminalCandidate.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("busy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["busy"] = false;
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["current"] = false;
        }
        if (!("recommended" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recommended"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChatCommandTerminalCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIChatCommandTerminalCandidate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIChatCommandTerminalCandidate(/** @type {Partial<AIChatCommandTerminalCandidate>} */($$parsedSource));
    }
}

export class AICollaborationPromptPreset {
    /**
     * Creates a new AICollaborationPromptPreset instance.
     * @param {Partial<AICollaborationPromptPreset>} [$$source = {}] - The source object to create the AICollaborationPromptPreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AICollaborationPromptPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AICollaborationPromptPreset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AICollaborationPromptPreset(/** @type {Partial<AICollaborationPromptPreset>} */($$parsedSource));
    }
}

export class AIConversationAPIMessage {
    /**
     * Creates a new AIConversationAPIMessage instance.
     * @param {Partial<AIConversationAPIMessage>} [$$source = {}] - The source object to create the AIConversationAPIMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["messageId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["uiMessageIds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["images"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AIConversationProviderCacheObjects | null | undefined}
             */
            this["cacheObjects"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["ts"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationAPIMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationAPIMessage}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("uiMessageIds" in $$parsedSource) {
            $$parsedSource["uiMessageIds"] = $$createField3_0($$parsedSource["uiMessageIds"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField4_0($$parsedSource["images"]);
        }
        if ("cacheObjects" in $$parsedSource) {
            $$parsedSource["cacheObjects"] = $$createField5_0($$parsedSource["cacheObjects"]);
        }
        return new AIConversationAPIMessage(/** @type {Partial<AIConversationAPIMessage>} */($$parsedSource));
    }
}

export class AIConversationAPIMessageTokenEntry {
    /**
     * Creates a new AIConversationAPIMessageTokenEntry instance.
     * @param {Partial<AIConversationAPIMessageTokenEntry>} [$$source = {}] - The source object to create the AIConversationAPIMessageTokenEntry.
     */
    constructor($$source = {}) {
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("rawTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rawTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationAPIMessageTokenEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationAPIMessageTokenEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationAPIMessageTokenEntry(/** @type {Partial<AIConversationAPIMessageTokenEntry>} */($$parsedSource));
    }
}

export class AIConversationBackup {
    /**
     * Creates a new AIConversationBackup instance.
     * @param {Partial<AIConversationBackup>} [$$source = {}] - The source object to create the AIConversationBackup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["messageRole"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationBackup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationBackup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationBackup(/** @type {Partial<AIConversationBackup>} */($$parsedSource));
    }
}

export class AIConversationContextCondenseResult {
    /**
     * Creates a new AIConversationContextCondenseResult instance.
     * @param {Partial<AIConversationContextCondenseResult>} [$$source = {}] - The source object to create the AIConversationContextCondenseResult.
     */
    constructor($$source = {}) {
        if (!("snapshot" in $$source)) {
            /**
             * @member
             * @type {AIConversationSnapshot}
             */
            this["snapshot"] = (new AIConversationSnapshot());
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("prevContextTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["prevContextTokens"] = 0;
        }
        if (!("newContextTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newContextTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationContextCondenseResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationContextCondenseResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField0_0($$parsedSource["snapshot"]);
        }
        return new AIConversationContextCondenseResult(/** @type {Partial<AIConversationContextCondenseResult>} */($$parsedSource));
    }
}

export class AIConversationContextMetrics {
    /**
     * Creates a new AIConversationContextMetrics instance.
     * @param {Partial<AIConversationContextMetrics>} [$$source = {}] - The source object to create the AIConversationContextMetrics.
     */
    constructor($$source = {}) {
        if (!("contextTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationContextMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationContextMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationContextMetrics(/** @type {Partial<AIConversationContextMetrics>} */($$parsedSource));
    }
}

export class AIConversationFollowUpOption {
    /**
     * Creates a new AIConversationFollowUpOption instance.
     * @param {Partial<AIConversationFollowUpOption>} [$$source = {}] - The source object to create the AIConversationFollowUpOption.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["answer"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["disabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["recommended"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationFollowUpOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationFollowUpOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationFollowUpOption(/** @type {Partial<AIConversationFollowUpOption>} */($$parsedSource));
    }
}

export class AIConversationFollowUpQuestion {
    /**
     * Creates a new AIConversationFollowUpQuestion instance.
     * @param {Partial<AIConversationFollowUpQuestion>} [$$source = {}] - The source object to create the AIConversationFollowUpQuestion.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AIConversationFollowUpOption[] | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationFollowUpQuestion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationFollowUpQuestion}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new AIConversationFollowUpQuestion(/** @type {Partial<AIConversationFollowUpQuestion>} */($$parsedSource));
    }
}

export class AIConversationMessage {
    /**
     * Creates a new AIConversationMessage instance.
     * @param {Partial<AIConversationMessage>} [$$source = {}] - The source object to create the AIConversationMessage.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["turnId"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["metrics"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["streaming"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["duration"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["actionLabel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["remainingFileEdits"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["purpose"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["command"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["images"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["response"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["requestId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["question"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AIConversationFollowUpQuestion[] | undefined}
             */
            this["questions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["suggestions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["extra"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationMessage}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField18_0 = $$createType0;
        const $$createField25_0 = $$createType7;
        const $$createField26_0 = $$createType0;
        const $$createField27_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField5_0($$parsedSource["metrics"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField18_0($$parsedSource["images"]);
        }
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField25_0($$parsedSource["questions"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField26_0($$parsedSource["suggestions"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField27_0($$parsedSource["extra"]);
        }
        return new AIConversationMessage(/** @type {Partial<AIConversationMessage>} */($$parsedSource));
    }
}

export class AIConversationMessageSearchResult {
    /**
     * Creates a new AIConversationMessageSearchResult instance.
     * @param {Partial<AIConversationMessageSearchResult>} [$$source = {}] - The source object to create the AIConversationMessageSearchResult.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("conversationTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationTitle"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationMessageSearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationMessageSearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationMessageSearchResult(/** @type {Partial<AIConversationMessageSearchResult>} */($$parsedSource));
    }
}

export class AIConversationOpenAIResponsesCacheObject {
    /**
     * Creates a new AIConversationOpenAIResponsesCacheObject instance.
     * @param {Partial<AIConversationOpenAIResponsesCacheObject>} [$$source = {}] - The source object to create the AIConversationOpenAIResponsesCacheObject.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["responseId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[] | undefined}
             */
            this["output"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["include"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["store"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["capturedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationOpenAIResponsesCacheObject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationOpenAIResponsesCacheObject}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("output" in $$parsedSource) {
            $$parsedSource["output"] = $$createField1_0($$parsedSource["output"]);
        }
        if ("include" in $$parsedSource) {
            $$parsedSource["include"] = $$createField2_0($$parsedSource["include"]);
        }
        return new AIConversationOpenAIResponsesCacheObject(/** @type {Partial<AIConversationOpenAIResponsesCacheObject>} */($$parsedSource));
    }
}

export class AIConversationProviderCacheObjects {
    /**
     * Creates a new AIConversationProviderCacheObjects instance.
     * @param {Partial<AIConversationProviderCacheObjects>} [$$source = {}] - The source object to create the AIConversationProviderCacheObjects.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AIConversationOpenAIResponsesCacheObject | null | undefined}
             */
            this["openaiResponses"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationProviderCacheObjects instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationProviderCacheObjects}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("openaiResponses" in $$parsedSource) {
            $$parsedSource["openaiResponses"] = $$createField0_0($$parsedSource["openaiResponses"]);
        }
        return new AIConversationProviderCacheObjects(/** @type {Partial<AIConversationProviderCacheObjects>} */($$parsedSource));
    }
}

export class AIConversationSnapshot {
    /**
     * Creates a new AIConversationSnapshot instance.
     * @param {Partial<AIConversationSnapshot>} [$$source = {}] - The source object to create the AIConversationSnapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("toolProtocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolProtocol"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["promptCacheBypassTimestamp"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentConversationId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rootConversationId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["relationType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["relationSource"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentTitleSnapshot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["archived"] = undefined;
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {AIConversationMessage[]}
             */
            this["messages"] = [];
        }
        if (!("apiMessages" in $$source)) {
            /**
             * @member
             * @type {AIConversationAPIMessage[]}
             */
            this["apiMessages"] = [];
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {AIConversationTaskSettings}
             */
            this["settings"] = (new AIConversationTaskSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType13;
        const $$createField14_0 = $$createType15;
        const $$createField15_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField13_0($$parsedSource["messages"]);
        }
        if ("apiMessages" in $$parsedSource) {
            $$parsedSource["apiMessages"] = $$createField14_0($$parsedSource["apiMessages"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField15_0($$parsedSource["settings"]);
        }
        return new AIConversationSnapshot(/** @type {Partial<AIConversationSnapshot>} */($$parsedSource));
    }
}

export class AIConversationSummary {
    /**
     * Creates a new AIConversationSummary instance.
     * @param {Partial<AIConversationSummary>} [$$source = {}] - The source object to create the AIConversationSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("toolProtocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolProtocol"] = "";
        }
        if (!("messageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messageCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["promptCacheBypassTimestamp"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentConversationId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rootConversationId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["relationType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["relationSource"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentTitleSnapshot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["archived"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationSummary(/** @type {Partial<AIConversationSummary>} */($$parsedSource));
    }
}

export class AIConversationSummarySubtaskResult {
    /**
     * Creates a new AIConversationSummarySubtaskResult instance.
     * @param {Partial<AIConversationSummarySubtaskResult>} [$$source = {}] - The source object to create the AIConversationSummarySubtaskResult.
     */
    constructor($$source = {}) {
        if (!("snapshot" in $$source)) {
            /**
             * @member
             * @type {AIConversationSnapshot}
             */
            this["snapshot"] = (new AIConversationSnapshot());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["continueText"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationSummarySubtaskResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationSummarySubtaskResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField0_0($$parsedSource["snapshot"]);
        }
        return new AIConversationSummarySubtaskResult(/** @type {Partial<AIConversationSummarySubtaskResult>} */($$parsedSource));
    }
}

export class AIConversationTaskSettings {
    /**
     * Creates a new AIConversationTaskSettings instance.
     * @param {Partial<AIConversationTaskSettings>} [$$source = {}] - The source object to create the AIConversationTaskSettings.
     */
    constructor($$source = {}) {
        if (!("currentProviderId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentProviderId"] = "";
        }
        if (!("autoApprovalEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoApprovalEnabled"] = false;
        }
        if (!("alwaysAllowReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowReadOnly"] = false;
        }
        if (!("alwaysAllowReadOnlyOutsideWorkspace" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowReadOnlyOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowWrite"] = false;
        }
        if (!("alwaysAllowWriteOutsideWorkspace" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowWriteOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWriteProtected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowWriteProtected"] = false;
        }
        if (!("alwaysAllowExecute" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowExecute"] = false;
        }
        if (!("alwaysAllowExecuteReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowExecuteReadOnly"] = false;
        }
        if (!("alwaysAllowExecuteAllCommands" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowExecuteAllCommands"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowedCommands"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["deniedCommands"] = undefined;
        }
        if (!("alwaysAllowMcp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowMcp"] = false;
        }
        if (!("alwaysAllowModeSwitch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowModeSwitch"] = false;
        }
        if (!("alwaysAllowSubtasks" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowSubtasks"] = false;
        }
        if (!("alwaysAllowFollowupQuestions" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowFollowupQuestions"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collaborationExtraPrompt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationTaskSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationTaskSettings}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedCommands" in $$parsedSource) {
            $$parsedSource["allowedCommands"] = $$createField10_0($$parsedSource["allowedCommands"]);
        }
        if ("deniedCommands" in $$parsedSource) {
            $$parsedSource["deniedCommands"] = $$createField11_0($$parsedSource["deniedCommands"]);
        }
        return new AIConversationTaskSettings(/** @type {Partial<AIConversationTaskSettings>} */($$parsedSource));
    }
}

export class AIConversationTokenLedger {
    /**
     * Creates a new AIConversationTokenLedger instance.
     * @param {Partial<AIConversationTokenLedger>} [$$source = {}] - The source object to create the AIConversationTokenLedger.
     */
    constructor($$source = {}) {
        if (!("systemRawTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["systemRawTokens"] = 0;
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {AIConversationAPIMessageTokenEntry[]}
             */
            this["entries"] = [];
        }
        if (!("contextTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationTokenLedger instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConversationTokenLedger}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new AIConversationTokenLedger(/** @type {Partial<AIConversationTokenLedger>} */($$parsedSource));
    }
}

export class AIGlobalSettings {
    /**
     * Creates a new AIGlobalSettings instance.
     * @param {Partial<AIGlobalSettings>} [$$source = {}] - The source object to create the AIGlobalSettings.
     */
    constructor($$source = {}) {
        if (!("currentProviderId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentProviderId"] = "";
        }
        if (!("autoApprovalEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoApprovalEnabled"] = false;
        }
        if (!("alwaysAllowReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowReadOnly"] = false;
        }
        if (!("alwaysAllowReadOnlyOutsideWorkspace" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowReadOnlyOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowWrite"] = false;
        }
        if (!("alwaysAllowWriteOutsideWorkspace" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowWriteOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWriteProtected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowWriteProtected"] = false;
        }
        if (!("alwaysAllowExecute" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowExecute"] = false;
        }
        if (!("alwaysAllowExecuteReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowExecuteReadOnly"] = false;
        }
        if (!("alwaysAllowExecuteAllCommands" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowExecuteAllCommands"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowedCommands"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["deniedCommands"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AISlashCommand[] | undefined}
             */
            this["slashCommands"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AICollaborationPromptPreset[] | undefined}
             */
            this["collaborationPromptPresets"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collaborationExtraPrompt"] = undefined;
        }
        if (!("alwaysAllowMcp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowMcp"] = false;
        }
        if (!("alwaysAllowModeSwitch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowModeSwitch"] = false;
        }
        if (!("alwaysAllowSubtasks" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowSubtasks"] = false;
        }
        if (!("alwaysAllowFollowupQuestions" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAllowFollowupQuestions"] = false;
        }
        if (!("soundEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["soundEnabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["soundVolume"] = undefined;
        }
        if (!("mcpEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mcpEnabled"] = false;
        }
        if (!("mcpAllowBrowserCalls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mcpAllowBrowserCalls"] = false;
        }
        if (!("terminalIsolation" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminalIsolation"] = false;
        }
        if (!("confirmDelete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmDelete"] = false;
        }
        if (!("continueAfterToolRejection" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["continueAfterToolRejection"] = false;
        }
        if (!("conversationAutoBackupEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["conversationAutoBackupEnabled"] = false;
        }
        if (!("messageActionBarAtBottom" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["messageActionBarAtBottom"] = false;
        }
        if (!("messageNavEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["messageNavEnabled"] = false;
        }
        if (!("approvalButtonOrder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["approvalButtonOrder"] = "";
        }
        if (!("commandActionButtonOrder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandActionButtonOrder"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["toolResultTokenThreshold"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["aiRequestProxyId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AIProxyNode[] | undefined}
             */
            this["proxyNodes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIGlobalSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIGlobalSettings}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType20;
        const $$createField13_0 = $$createType22;
        const $$createField34_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedCommands" in $$parsedSource) {
            $$parsedSource["allowedCommands"] = $$createField10_0($$parsedSource["allowedCommands"]);
        }
        if ("deniedCommands" in $$parsedSource) {
            $$parsedSource["deniedCommands"] = $$createField11_0($$parsedSource["deniedCommands"]);
        }
        if ("slashCommands" in $$parsedSource) {
            $$parsedSource["slashCommands"] = $$createField12_0($$parsedSource["slashCommands"]);
        }
        if ("collaborationPromptPresets" in $$parsedSource) {
            $$parsedSource["collaborationPromptPresets"] = $$createField13_0($$parsedSource["collaborationPromptPresets"]);
        }
        if ("proxyNodes" in $$parsedSource) {
            $$parsedSource["proxyNodes"] = $$createField34_0($$parsedSource["proxyNodes"]);
        }
        return new AIGlobalSettings(/** @type {Partial<AIGlobalSettings>} */($$parsedSource));
    }
}

export class AIProviderProfile {
    /**
     * Creates a new AIProviderProfile instance.
     * @param {Partial<AIProviderProfile>} [$$source = {}] - The source object to create the AIProviderProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("cacheStrategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cacheStrategy"] = "";
        }
        if (!("webSearchEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["webSearchEnabled"] = false;
        }
        if (!("dedicatedWebSearchEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dedicatedWebSearchEnabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dedicatedWebSearchProviderId"] = undefined;
        }
        if (!("dedicatedProxyEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dedicatedProxyEnabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dedicatedProxyId"] = undefined;
        }
        if (!("reasoningEffort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reasoningEffort"] = "";
        }
        if (!("enableReasoningEffort" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableReasoningEffort"] = false;
        }
        if (!("openAiLegacyReasoningFormatEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["openAiLegacyReasoningFormatEnabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["modelMaxTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["modelMaxThinkingTokens"] = undefined;
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["builtin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["builtinLoginUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["apiKeyField"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIProviderProfile}
     */
    static createFrom($$source = {}) {
        const $$createField20_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiKeyField" in $$parsedSource) {
            $$parsedSource["apiKeyField"] = $$createField20_0($$parsedSource["apiKeyField"]);
        }
        return new AIProviderProfile(/** @type {Partial<AIProviderProfile>} */($$parsedSource));
    }
}

export class AIProviderState {
    /**
     * Creates a new AIProviderState instance.
     * @param {Partial<AIProviderState>} [$$source = {}] - The source object to create the AIProviderState.
     */
    constructor($$source = {}) {
        if (!("currentProviderId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentProviderId"] = "";
        }
        if (!("providers" in $$source)) {
            /**
             * @member
             * @type {AIProviderProfile[]}
             */
            this["providers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIProviderState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField1_0($$parsedSource["providers"]);
        }
        return new AIProviderState(/** @type {Partial<AIProviderState>} */($$parsedSource));
    }
}

export class AIProviderWebSearchValidationResult {
    /**
     * Creates a new AIProviderWebSearchValidationResult instance.
     * @param {Partial<AIProviderWebSearchValidationResult>} [$$source = {}] - The source object to create the AIProviderWebSearchValidationResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["actualTitle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rawOutput"] = undefined;
        }
        if (!("expectedTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expectedTitle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderWebSearchValidationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIProviderWebSearchValidationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProviderWebSearchValidationResult(/** @type {Partial<AIProviderWebSearchValidationResult>} */($$parsedSource));
    }
}

export class AIProxyNode {
    /**
     * Creates a new AIProxyNode instance.
     * @param {Partial<AIProxyNode>} [$$source = {}] - The source object to create the AIProxyNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProxyNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIProxyNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProxyNode(/** @type {Partial<AIProxyNode>} */($$parsedSource));
    }
}

export class AISlashCommand {
    /**
     * Creates a new AISlashCommand instance.
     * @param {Partial<AISlashCommand>} [$$source = {}] - The source object to create the AISlashCommand.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISlashCommand instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AISlashCommand}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISlashCommand(/** @type {Partial<AISlashCommand>} */($$parsedSource));
    }
}

export class ThemeToolRequest {
    /**
     * Creates a new ThemeToolRequest instance.
     * @param {Partial<ThemeToolRequest>} [$$source = {}] - The source object to create the ThemeToolRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["conversationId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["requestId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["action"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["slot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["request"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeToolRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeToolRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeToolRequest(/** @type {Partial<ThemeToolRequest>} */($$parsedSource));
    }
}

export class ThemeToolResult {
    /**
     * Creates a new ThemeToolResult instance.
     * @param {Partial<ThemeToolResult>} [$$source = {}] - The source object to create the ThemeToolResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["action"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["draftId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["slot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sourceThemeId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["theme"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["appliedPaths"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["warnings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["invalidPaths"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["suggestedPaths"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["fieldMap"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["settings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["committedTheme"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["result"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeToolResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeToolResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType8;
        const $$createField11_0 = $$createType8;
        const $$createField12_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("theme" in $$parsedSource) {
            $$parsedSource["theme"] = $$createField5_0($$parsedSource["theme"]);
        }
        if ("appliedPaths" in $$parsedSource) {
            $$parsedSource["appliedPaths"] = $$createField6_0($$parsedSource["appliedPaths"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        if ("invalidPaths" in $$parsedSource) {
            $$parsedSource["invalidPaths"] = $$createField8_0($$parsedSource["invalidPaths"]);
        }
        if ("suggestedPaths" in $$parsedSource) {
            $$parsedSource["suggestedPaths"] = $$createField9_0($$parsedSource["suggestedPaths"]);
        }
        if ("fieldMap" in $$parsedSource) {
            $$parsedSource["fieldMap"] = $$createField10_0($$parsedSource["fieldMap"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField11_0($$parsedSource["settings"]);
        }
        if ("committedTheme" in $$parsedSource) {
            $$parsedSource["committedTheme"] = $$createField12_0($$parsedSource["committedTheme"]);
        }
        return new ThemeToolResult(/** @type {Partial<ThemeToolResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AIConversationProviderCacheObjects.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = AIConversationSnapshot.createFrom;
const $$createType4 = AIConversationFollowUpOption.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = AIConversationFollowUpQuestion.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = AIConversationOpenAIResponsesCacheObject.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = AIConversationMessage.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = AIConversationAPIMessage.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = AIConversationTaskSettings.createFrom;
const $$createType17 = AIConversationAPIMessageTokenEntry.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = AISlashCommand.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = AICollaborationPromptPreset.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = AIProxyNode.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = AIProviderProfile.createFrom;
const $$createType26 = $Create.Array($$createType25);
