// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class OwnershipCandidateEntry {
    /**
     * Creates a new OwnershipCandidateEntry instance.
     * @param {Partial<OwnershipCandidateEntry>} [$$source = {}] - The source object to create the OwnershipCandidateEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OwnershipCandidateEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OwnershipCandidateEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OwnershipCandidateEntry(/** @type {Partial<OwnershipCandidateEntry>} */($$parsedSource));
    }
}

export class OwnershipCandidates {
    /**
     * Creates a new OwnershipCandidates instance.
     * @param {Partial<OwnershipCandidates>} [$$source = {}] - The source object to create the OwnershipCandidates.
     */
    constructor($$source = {}) {
        if (!("users" in $$source)) {
            /**
             * @member
             * @type {OwnershipCandidateEntry[]}
             */
            this["users"] = [];
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {OwnershipCandidateEntry[]}
             */
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OwnershipCandidates instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OwnershipCandidates}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("users" in $$parsedSource) {
            $$parsedSource["users"] = $$createField0_0($$parsedSource["users"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField1_0($$parsedSource["groups"]);
        }
        return new OwnershipCandidates(/** @type {Partial<OwnershipCandidates>} */($$parsedSource));
    }
}

export class PathOwnershipInfo {
    /**
     * Creates a new PathOwnershipInfo instance.
     * @param {Partial<PathOwnershipInfo>} [$$source = {}] - The source object to create the PathOwnershipInfo.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("gid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gid"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("permission" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["permission"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathOwnershipInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PathOwnershipInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathOwnershipInfo(/** @type {Partial<PathOwnershipInfo>} */($$parsedSource));
    }
}

export class PortForwardInfo {
    /**
     * Creates a new PortForwardInfo instance.
     * @param {Partial<PortForwardInfo>} [$$source = {}] - The source object to create the PortForwardInfo.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Kind"] = "";
        }
        if (!("Addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Addr"] = "";
        }
        if (!("LocalAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LocalAddr"] = "";
        }
        if (!("RemoteAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RemoteAddr"] = "";
        }
        if (!("LocalHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LocalHost"] = "";
        }
        if (!("LocalPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LocalPort"] = "";
        }
        if (!("RemoteHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RemoteHost"] = "";
        }
        if (!("RemotePort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RemotePort"] = "";
        }
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForwardInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardInfo(/** @type {Partial<PortForwardInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = OwnershipCandidateEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
