// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnectedSession {
    /**
     * Creates a new ConnectedSession instance.
     * @param {Partial<ConnectedSession>} [$$source = {}] - The source object to create the ConnectedSession.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group_session_id"] = undefined;
        }
        if (!("connection_ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_ref"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["connection_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (!("sftp_available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sftp_available"] = false;
        }
        if (!("is_child_terminal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_child_terminal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectedSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectedSession}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new ConnectedSession(/** @type {Partial<ConnectedSession>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
