// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProgramFontInfo 描述一个已安装的程序内置字体。
 */
export class ProgramFontInfo {
    /**
     * Creates a new ProgramFontInfo instance.
     * @param {Partial<ProgramFontInfo>} [$$source = {}] - The source object to create the ProgramFontInfo.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgramFontInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProgramFontInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgramFontInfo(/** @type {Partial<ProgramFontInfo>} */($$parsedSource));
    }
}
