// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {wailsapp} from '../models';
import {sshmanager} from '../models';
import {aitypes} from '../models';
import {runtimeenv} from '../models';
import {context} from '../models';
import {ai} from '../models';
import {programfonts} from '../models';
import {mcpserver} from '../models';
import {mcp} from '../models';

export function AbortChunkedUploadFile(arg1:string,arg2:string):Promise<void>;

export function AbortChunkedUploadTask(arg1:string):Promise<void>;

export function AbortCompressedUpload(arg1:string):Promise<void>;

export function AbortDownloadTransfer(arg1:string):Promise<void>;

export function AcceptHostKeyChange(arg1:string,arg2:number):Promise<void>;

export function AckClose():Promise<void>;

export function AutoRepairCompressedUploadTargets(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function BackupToFTP():Promise<Record<string, any>>;

export function BackupToR2():Promise<Record<string, any>>;

export function BackupToSFTP():Promise<Record<string, any>>;

export function BackupToWebdav():Promise<Record<string, any>>;

export function BatchDeleteConnections(arg1:Array<string>):Promise<void>;

export function BatchDeleteItemShell(arg1:string,arg2:Array<string>):Promise<void>;

export function BatchSetConnectionGroup(arg1:Array<string>,arg2:string):Promise<void>;

export function BeginChunkedUploadFile(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function BeginChunkedUploadTask(arg1:string,arg2:string,arg3:number):Promise<string>;

export function ChangeRecoveryPassword(arg1:string):Promise<void>;

export function ChmodFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ChownFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CleanupSession(arg1:string):Promise<void>;

export function ClearTombstoneConflicts(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function ClearWorkspaceState():Promise<void>;

export function ClipboardGetText():Promise<string>;

export function CompleteChunkedUploadFile(arg1:string,arg2:string):Promise<void>;

export function CompressItem(arg1:string,arg2:string):Promise<void>;

export function ConnectLocal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ConnectSSH(arg1:string,arg2:string):Promise<void>;

export function ConnectSerial(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:string):Promise<void>;

export function CopyItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CopyThemePackageToMode(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeleteConnection(arg1:string):Promise<boolean>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteItem(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteItemShell(arg1:string,arg2:string):Promise<void>;

export function DeleteMCPGlobalServer(arg1:string):Promise<void>;

export function DeletePortForwardForSession(arg1:string,arg2:string):Promise<void>;

export function DeleteProgramFont(arg1:string):Promise<void>;

export function DeleteThemePackage(arg1:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DisconnectSSHConnection(arg1:string,arg2:Array<string>):Promise<void>;

export function DoQuit():Promise<void>;

export function DownloadDirectoryCompressed(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DownloadDirectoryToLocal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFileToLocal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DownloadImportTemplate(arg1:string):Promise<string>;

export function EnsureRemoteDirAndRetrySync():Promise<string>;

export function ExportConnections(arg1:boolean,arg2:string):Promise<string>;

export function ExportConnectionsByIDs(arg1:Array<string>,arg2:boolean,arg3:string):Promise<string>;

export function FinishChunkedUploadTask(arg1:string):Promise<void>;

export function GetArch():Promise<string>;

export function GetAutoSyncEnabled():Promise<boolean>;

export function GetChmodDialogSettings():Promise<Record<string, any>>;

export function GetCommandHistory(arg1:string):Promise<string>;

export function GetConnectionByID(arg1:string):Promise<config.Connection>;

export function GetConnectionPassword(arg1:string):Promise<string>;

export function GetConnections():Promise<Array<config.Connection>>;

export function GetConnectionsMasked():Promise<Array<config.Connection>>;

export function GetCredentials():Promise<Array<config.Credential>>;

export function GetFTPConfig():Promise<Record<string, any>>;

export function GetFileManagerSettings():Promise<Record<string, any>>;

export function GetFullProcessList(arg1:string):Promise<Array<Record<string, any>>>;

export function GetGitHubContributors():Promise<Array<wailsapp.GitHubContributor>>;

export function GetGlobalCommandHistory():Promise<string>;

export function GetLastSyncTime():Promise<number>;

export function GetLiveWorkspaceState():Promise<string>;

export function GetLocalShells():Promise<Array<string>>;

export function GetMCPEmbeddedFirecrawlAPIKey():Promise<string>;

export function GetMCPOutputCompressionSettings():Promise<Record<string, number>>;

export function GetMCPServerInfo():Promise<Record<string, any>>;

export function GetMCPSettingsState():Promise<Record<string, any>>;

export function GetParamHistory():Promise<string>;

export function GetPathOwnership(arg1:string,arg2:string):Promise<sshmanager.PathOwnershipInfo>;

export function GetProcessEnv(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProgramDirectory():Promise<string>;

export function GetProgramFontDataURL(arg1:string):Promise<string>;

export function GetProxyNodes():Promise<Array<aitypes.AIProxyNode>>;

export function GetQuickCommands():Promise<string>;

export function GetR2Config():Promise<Record<string, any>>;

export function GetRecoveryPassword():Promise<string>;

export function GetRememberWorkspace():Promise<boolean>;

export function GetRuntimeEnvironmentSettings():Promise<runtimeenv.Settings>;

export function GetRuntimeEnvironmentStatus():Promise<runtimeenv.Status>;

export function GetSFTPConfig():Promise<Record<string, any>>;

export function GetSSHChannelUsage(arg1:string):Promise<Record<string, any>>;

export function GetServerStaticInfo(arg1:string):Promise<Record<string, any>>;

export function GetSyncMode():Promise<string>;

export function GetSyncTombstoneStats():Promise<config.SyncTombstoneStats>;

export function GetTasksDir():Promise<string>;

export function GetTerminalCwd(arg1:string):Promise<string>;

export function GetThemePackageSettings():Promise<Record<string, any>>;

export function GetThemePackagesDirectory():Promise<string>;

export function GetWebdavConfig():Promise<Record<string, string>>;

export function GetWebviewGpuDisabled():Promise<boolean>;

export function GetWorkspacePersistenceLevel():Promise<string>;

export function GetWorkspaceSessionState(arg1:string):Promise<string>;

export function GetWorkspaceState():Promise<string>;

export function GetWsPort():Promise<number>;

export function GetWsToken():Promise<string>;

export function HandleThemeToolRequest(arg1:context.Context,arg2:ai.ThemeToolRequest):Promise<ai.ThemeToolResult>;

export function HasRecoveryPassword():Promise<boolean>;

export function ImportConnections(arg1:string,arg2:string):Promise<config.ImportResult>;

export function ImportProgramFontFiles(arg1:Array<string>):Promise<Array<programfonts.ProgramFontInfo>>;

export function ImportThemePackageFiles(arg1:Array<string>):Promise<Array<Record<string, any>>>;

export function InstallRuntimeEnvironment(arg1:string):Promise<runtimeenv.Status>;

export function InstallUnzip(arg1:string):Promise<void>;

export function IsCustomTasksDir():Promise<boolean>;

export function IsPortableVersion():Promise<boolean>;

export function KillProcess(arg1:string,arg2:string):Promise<void>;

export function ListConnectedSessions():Promise<Array<mcpserver.ConnectedSession>>;

export function ListDir(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ListExternalEditSessions():Promise<Array<Record<string, any>>>;

export function ListFTPBackups():Promise<Array<Record<string, any>>>;

export function ListOwnershipCandidates(arg1:string):Promise<sshmanager.OwnershipCandidates>;

export function ListPortForwards(arg1:string):Promise<Array<sshmanager.PortForwardInfo>>;

export function ListProgramFonts():Promise<Array<programfonts.ProgramFontInfo>>;

export function ListR2Backups():Promise<Array<Record<string, any>>>;

export function ListSFTPBackups():Promise<Array<Record<string, any>>>;

export function ListSerialPorts():Promise<Array<string>>;

export function ListThemePackages():Promise<Array<Record<string, any>>>;

export function ListWebdavBackups():Promise<Array<Record<string, any>>>;

export function MarkThemeToolConversationUserConfirmed(arg1:string):Promise<void>;

export function MigrateAITasksDir(arg1:string):Promise<void>;

export function Mkdir(arg1:string,arg2:string):Promise<void>;

export function MoveItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NetworkInfo(arg1:string):Promise<Record<string, any>>;

export function OpenLocalPathInExplorer(arg1:string,arg2:boolean):Promise<void>;

export function OpenRemoteFileInSystemEditor(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Record<string, any>>;

export function OpenRemoteFileWithEditor(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<Record<string, any>>;

export function OpenTerminal(arg1:string):Promise<string>;

export function PingServer(arg1:string,arg2:string):Promise<Record<string, any>>;

export function PreviewDownloadConflicts(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<Record<string, any>>>;

export function PreviewSmartUncompressItem(arg1:string,arg2:string):Promise<Record<string, any>>;

export function PreviewTombstoneConflicts():Promise<config.TombstoneConflictPreview>;

export function PruneSyncTombstones(arg1:number):Promise<config.SyncTombstonePruneResult>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function ReadPrivateKeyFile():Promise<string>;

export function ReconnectWithPassword(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ReloadMCPGlobalServers():Promise<void>;

export function RenameConnectionGroup(arg1:string,arg2:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetRecoveryPassword(arg1:string):Promise<void>;

export function ResetTasksDir():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveDirectoryPath(arg1:string,arg2:string):Promise<string>;

export function ResolveDownloadLocalPath(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function ResolveDownloadPath(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<string>;

export function ResolveMCPApproval(arg1:string,arg2:boolean):Promise<void>;

export function RestartMCPClientServer(arg1:string,arg2:string):Promise<void>;

export function RestartPortForwardForSession(arg1:string,arg2:string):Promise<string>;

export function RestoreFromFTPFile(arg1:string):Promise<Record<string, any>>;

export function RestoreFromFTPFileWithPassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RestoreFromR2File(arg1:string):Promise<Record<string, any>>;

export function RestoreFromR2FileWithPassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RestoreFromSFTPFile(arg1:string):Promise<Record<string, any>>;

export function RestoreFromSFTPFileWithPassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RestoreFromWebdavFile(arg1:string):Promise<Record<string, any>>;

export function RestoreFromWebdavFileWithPassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RetrySync():Promise<string>;

export function SaveChmodDialogSettings(arg1:string,arg2:boolean):Promise<void>;

export function SaveCommandHistory(arg1:string,arg2:string):Promise<void>;

export function SaveConnection(arg1:config.Connection,arg2:boolean):Promise<config.Connection>;

export function SaveCredential(arg1:config.Credential):Promise<config.Credential>;

export function SaveFTPConfig(arg1:Record<string, string>):Promise<void>;

export function SaveGlobalCommandHistory(arg1:string):Promise<void>;

export function SaveMCPEmbeddedFirecrawlAPIKey(arg1:string):Promise<void>;

export function SaveMCPGlobalServer(arg1:string,arg2:string):Promise<void>;

export function SaveMCPOutputCompressionSettings(arg1:number,arg2:number):Promise<void>;

export function SaveParamHistory(arg1:string):Promise<void>;

export function SaveProxyNodes(arg1:string):Promise<void>;

export function SaveQuickCommands(arg1:string):Promise<void>;

export function SaveQuickCommandsLocal(arg1:string):Promise<void>;

export function SaveR2Config(arg1:Record<string, string>):Promise<void>;

export function SaveRuntimeEnvironmentSettings(arg1:string):Promise<void>;

export function SaveSFTPConfig(arg1:Record<string, string>):Promise<void>;

export function SaveThemePackageSettings(arg1:Record<string, string>):Promise<void>;

export function SaveTransferTuningSettings(arg1:number,arg2:number,arg3:boolean,arg4:boolean):Promise<void>;

export function SaveWebdavConfig(arg1:Record<string, string>):Promise<void>;

export function SaveWorkspaceSessionState(arg1:string,arg2:string):Promise<void>;

export function SaveWorkspaceState(arg1:string):Promise<void>;

export function SelectDownloadDirectory(arg1:string):Promise<string>;

export function SelectDownloadFilePath(arg1:string,arg2:string):Promise<string>;

export function SelectExternalEditor():Promise<string>;

export function SelectImportFile():Promise<string>;

export function SelectProgramFontFiles():Promise<Array<string>>;

export function SelectTasksDirectory():Promise<string>;

export function SelectThemePackageFiles():Promise<Array<string>>;

export function SelectUploadDirectory():Promise<string>;

export function SelectUploadFiles():Promise<Array<string>>;

export function SetAutoSyncEnabled(arg1:boolean):Promise<void>;

export function SetChmodAutoApplyLastSettings(arg1:boolean):Promise<void>;

export function SetConnectionGroup(arg1:string,arg2:string):Promise<void>;

export function SetConnectionOS(arg1:string,arg2:string):Promise<void>;

export function SetFileManagerAutoRefreshDisabled(arg1:boolean):Promise<void>;

export function SetFileManagerDoubleClickUncompressArchive(arg1:boolean):Promise<void>;

export function SetFileManagerMaxEditSize(arg1:number):Promise<void>;

export function SetFileManagerSmartUncompressConflictStrategy(arg1:string):Promise<void>;

export function SetLiveWorkspaceState(arg1:string):Promise<void>;

export function SetRecoveryPassword(arg1:string):Promise<void>;

export function SetRememberWorkspace(arg1:boolean):Promise<void>;

export function SetSyncMode(arg1:string):Promise<void>;

export function SetWebviewGpuDisabled(arg1:boolean):Promise<void>;

export function SetWorkspacePersistenceLevel(arg1:string):Promise<void>;

export function StartLocalPortForward(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartRemotePortForward(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopExternalEdit(arg1:string,arg2:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function StopPortForwardForSession(arg1:string,arg2:string):Promise<void>;

export function SupportsWebviewGpuDisable():Promise<boolean>;

export function SyncAllProviders():Promise<Record<string, any>>;

export function SyncFromFTP():Promise<Record<string, any>>;

export function SyncFromR2():Promise<Record<string, any>>;

export function SyncFromSFTP():Promise<Record<string, any>>;

export function SyncFromWebdav():Promise<Record<string, any>>;

export function SyncWithRecoveryPassword(arg1:string):Promise<Record<string, any>>;

export function SystemInfo(arg1:string):Promise<Record<string, any>>;
export function SystemInfoLite(arg1:string):Promise<Record<string, any>>;

export function TestFTPConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<config.FTPConnectionTestResult>;

export function TestFTPConnectionWithCertificateApproval(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<config.FTPConnectionTestResult>;

export function TestR2Connection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TestSFTPConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<config.SFTPConnectionTestResult>;

export function TestSFTPConnectionWithHostKeyApproval(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<config.SFTPConnectionTestResult>;

export function TestWebdavConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ToggleMCPClientServer(arg1:string,arg2:string,arg3:boolean):Promise<mcp.ServerRuntime>;

export function ToggleMCPClientServerDisabledForPrompts(arg1:string,arg2:string,arg3:boolean):Promise<mcp.ServerRuntime>;

export function ToggleMCPClientServerToolDisabledForPrompts(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<mcp.ServerRuntime>;

export function UncompressItem(arg1:string,arg2:string):Promise<void>;

export function UncompressItemWithStrategy(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateApp(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateMCPClientServerTimeout(arg1:string,arg2:string,arg3:number):Promise<mcp.ServerRuntime>;

export function UploadChunkBase64(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;

export function UploadFileContent(arg1:string,arg2:string,arg3:string,arg4:Array<number>):Promise<void>;

export function UploadFileContentBase64(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadLocalDir(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadLocalFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadLocalPathsCompressed(arg1:string,arg2:string,arg3:number,arg4:Array<string>,arg5:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteWsOutput(arg1:string,arg2:Array<number>):Promise<void>;
