// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortChunkedUploadFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['AbortChunkedUploadFile'](arg1, arg2);
}

export function AbortChunkedUploadTask(arg1) {
  return window['go']['wailsapp']['App']['AbortChunkedUploadTask'](arg1);
}

export function AbortCompressedUpload(arg1) {
  return window['go']['wailsapp']['App']['AbortCompressedUpload'](arg1);
}

export function AbortDownloadTransfer(arg1) {
  return window['go']['wailsapp']['App']['AbortDownloadTransfer'](arg1);
}

export function AcceptHostKeyChange(arg1, arg2) {
  return window['go']['wailsapp']['App']['AcceptHostKeyChange'](arg1, arg2);
}

export function AckClose() {
  return window['go']['wailsapp']['App']['AckClose']();
}

export function AutoRepairCompressedUploadTargets(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['AutoRepairCompressedUploadTargets'](arg1, arg2, arg3);
}

export function BackupToFTP() {
  return window['go']['wailsapp']['App']['BackupToFTP']();
}

export function BackupToR2() {
  return window['go']['wailsapp']['App']['BackupToR2']();
}

export function BackupToSFTP() {
  return window['go']['wailsapp']['App']['BackupToSFTP']();
}

export function BackupToWebdav() {
  return window['go']['wailsapp']['App']['BackupToWebdav']();
}

export function BatchDeleteConnections(arg1) {
  return window['go']['wailsapp']['App']['BatchDeleteConnections'](arg1);
}

export function BatchDeleteItemShell(arg1, arg2) {
  return window['go']['wailsapp']['App']['BatchDeleteItemShell'](arg1, arg2);
}

export function BatchSetConnectionGroup(arg1, arg2) {
  return window['go']['wailsapp']['App']['BatchSetConnectionGroup'](arg1, arg2);
}

export function BeginChunkedUploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['BeginChunkedUploadFile'](arg1, arg2, arg3, arg4);
}

export function BeginChunkedUploadTask(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['BeginChunkedUploadTask'](arg1, arg2, arg3);
}

export function ChangeRecoveryPassword(arg1) {
  return window['go']['wailsapp']['App']['ChangeRecoveryPassword'](arg1);
}

export function ChmodFile(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['ChmodFile'](arg1, arg2, arg3, arg4);
}

export function ChownFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['ChownFile'](arg1, arg2, arg3, arg4, arg5);
}

export function CleanupSession(arg1) {
  return window['go']['wailsapp']['App']['CleanupSession'](arg1);
}

export function ClearTombstoneConflicts(arg1, arg2) {
  return window['go']['wailsapp']['App']['ClearTombstoneConflicts'](arg1, arg2);
}

export function ClearWorkspaceState() {
  return window['go']['wailsapp']['App']['ClearWorkspaceState']();
}

export function ClipboardGetText() {
  return window['go']['wailsapp']['App']['ClipboardGetText']();
}

export function CompleteChunkedUploadFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['CompleteChunkedUploadFile'](arg1, arg2);
}

export function CompressItem(arg1, arg2) {
  return window['go']['wailsapp']['App']['CompressItem'](arg1, arg2);
}

export function ConnectLocal(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['ConnectLocal'](arg1, arg2, arg3, arg4);
}

export function ConnectSSH(arg1, arg2) {
  return window['go']['wailsapp']['App']['ConnectSSH'](arg1, arg2);
}

export function ConnectSerial(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailsapp']['App']['ConnectSerial'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CopyItem(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['CopyItem'](arg1, arg2, arg3);
}

export function CopyThemePackageToMode(arg1, arg2) {
  return window['go']['wailsapp']['App']['CopyThemePackageToMode'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['wailsapp']['App']['DeleteConnection'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['wailsapp']['App']['DeleteCredential'](arg1);
}

export function DeleteItem(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['DeleteItem'](arg1, arg2, arg3);
}

export function DeleteItemShell(arg1, arg2) {
  return window['go']['wailsapp']['App']['DeleteItemShell'](arg1, arg2);
}

export function DeleteMCPGlobalServer(arg1) {
  return window['go']['wailsapp']['App']['DeleteMCPGlobalServer'](arg1);
}

export function DeletePortForwardForSession(arg1, arg2) {
  return window['go']['wailsapp']['App']['DeletePortForwardForSession'](arg1, arg2);
}

export function DeleteProgramFont(arg1) {
  return window['go']['wailsapp']['App']['DeleteProgramFont'](arg1);
}

export function DeleteThemePackage(arg1) {
  return window['go']['wailsapp']['App']['DeleteThemePackage'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['wailsapp']['App']['DisconnectSSH'](arg1);
}

export function DisconnectSSHConnection(arg1, arg2) {
  return window['go']['wailsapp']['App']['DisconnectSSHConnection'](arg1, arg2);
}

export function DoQuit() {
  return window['go']['wailsapp']['App']['DoQuit']();
}

export function DownloadDirectoryCompressed(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['DownloadDirectoryCompressed'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadDirectoryToLocal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['DownloadDirectoryToLocal'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadFileToLocal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['DownloadFileToLocal'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadImportTemplate(arg1) {
  return window['go']['wailsapp']['App']['DownloadImportTemplate'](arg1);
}

export function EnsureRemoteDirAndRetrySync() {
  return window['go']['wailsapp']['App']['EnsureRemoteDirAndRetrySync']();
}

export function ExportConnections(arg1, arg2) {
  return window['go']['wailsapp']['App']['ExportConnections'](arg1, arg2);
}

export function ExportConnectionsByIDs(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ExportConnectionsByIDs'](arg1, arg2, arg3);
}

export function FinishChunkedUploadTask(arg1) {
  return window['go']['wailsapp']['App']['FinishChunkedUploadTask'](arg1);
}

export function GetArch() {
  return window['go']['wailsapp']['App']['GetArch']();
}

export function GetAutoSyncEnabled() {
  return window['go']['wailsapp']['App']['GetAutoSyncEnabled']();
}

export function GetChmodDialogSettings() {
  return window['go']['wailsapp']['App']['GetChmodDialogSettings']();
}

export function GetCommandHistory(arg1) {
  return window['go']['wailsapp']['App']['GetCommandHistory'](arg1);
}

export function GetConnectionByID(arg1) {
  return window['go']['wailsapp']['App']['GetConnectionByID'](arg1);
}

export function GetConnectionPassword(arg1) {
  return window['go']['wailsapp']['App']['GetConnectionPassword'](arg1);
}

export function GetConnections() {
  return window['go']['wailsapp']['App']['GetConnections']();
}

export function GetConnectionsMasked() {
  return window['go']['wailsapp']['App']['GetConnectionsMasked']();
}

export function GetCredentials() {
  return window['go']['wailsapp']['App']['GetCredentials']();
}

export function GetFTPConfig() {
  return window['go']['wailsapp']['App']['GetFTPConfig']();
}

export function GetFileManagerSettings() {
  return window['go']['wailsapp']['App']['GetFileManagerSettings']();
}

export function GetFullProcessList(arg1) {
  return window['go']['wailsapp']['App']['GetFullProcessList'](arg1);
}

export function GetGitHubContributors() {
  return window['go']['wailsapp']['App']['GetGitHubContributors']();
}

export function GetGlobalCommandHistory() {
  return window['go']['wailsapp']['App']['GetGlobalCommandHistory']();
}

export function GetLastSyncTime() {
  return window['go']['wailsapp']['App']['GetLastSyncTime']();
}

export function GetLiveWorkspaceState() {
  return window['go']['wailsapp']['App']['GetLiveWorkspaceState']();
}

export function GetLocalShells() {
  return window['go']['wailsapp']['App']['GetLocalShells']();
}

export function GetMCPEmbeddedFirecrawlAPIKey() {
  return window['go']['wailsapp']['App']['GetMCPEmbeddedFirecrawlAPIKey']();
}

export function GetMCPOutputCompressionSettings() {
  return window['go']['wailsapp']['App']['GetMCPOutputCompressionSettings']();
}

export function GetMCPServerInfo() {
  return window['go']['wailsapp']['App']['GetMCPServerInfo']();
}

export function GetMCPSettingsState() {
  return window['go']['wailsapp']['App']['GetMCPSettingsState']();
}

export function GetParamHistory() {
  return window['go']['wailsapp']['App']['GetParamHistory']();
}

export function GetPathOwnership(arg1, arg2) {
  return window['go']['wailsapp']['App']['GetPathOwnership'](arg1, arg2);
}

export function GetProcessEnv(arg1, arg2) {
  return window['go']['wailsapp']['App']['GetProcessEnv'](arg1, arg2);
}

export function GetProgramDirectory() {
  return window['go']['wailsapp']['App']['GetProgramDirectory']();
}

export function GetProgramFontDataURL(arg1) {
  return window['go']['wailsapp']['App']['GetProgramFontDataURL'](arg1);
}

export function GetProxyNodes() {
  return window['go']['wailsapp']['App']['GetProxyNodes']();
}

export function GetQuickCommands() {
  return window['go']['wailsapp']['App']['GetQuickCommands']();
}

export function GetR2Config() {
  return window['go']['wailsapp']['App']['GetR2Config']();
}

export function GetRecoveryPassword() {
  return window['go']['wailsapp']['App']['GetRecoveryPassword']();
}

export function GetRememberWorkspace() {
  return window['go']['wailsapp']['App']['GetRememberWorkspace']();
}

export function GetRuntimeEnvironmentSettings() {
  return window['go']['wailsapp']['App']['GetRuntimeEnvironmentSettings']();
}

export function GetRuntimeEnvironmentStatus() {
  return window['go']['wailsapp']['App']['GetRuntimeEnvironmentStatus']();
}

export function GetSFTPConfig() {
  return window['go']['wailsapp']['App']['GetSFTPConfig']();
}

export function GetSSHChannelUsage(arg1) {
  return window['go']['wailsapp']['App']['GetSSHChannelUsage'](arg1);
}

export function GetServerStaticInfo(arg1) {
  return window['go']['wailsapp']['App']['GetServerStaticInfo'](arg1);
}

export function GetSyncMode() {
  return window['go']['wailsapp']['App']['GetSyncMode']();
}

export function GetSyncTombstoneStats() {
  return window['go']['wailsapp']['App']['GetSyncTombstoneStats']();
}

export function GetTasksDir() {
  return window['go']['wailsapp']['App']['GetTasksDir']();
}

export function GetTerminalCwd(arg1) {
  return window['go']['wailsapp']['App']['GetTerminalCwd'](arg1);
}

export function GetThemePackageSettings() {
  return window['go']['wailsapp']['App']['GetThemePackageSettings']();
}

export function GetThemePackagesDirectory() {
  return window['go']['wailsapp']['App']['GetThemePackagesDirectory']();
}

export function GetWebdavConfig() {
  return window['go']['wailsapp']['App']['GetWebdavConfig']();
}

export function GetWebviewGpuDisabled() {
  return window['go']['wailsapp']['App']['GetWebviewGpuDisabled']();
}

export function GetWorkspacePersistenceLevel() {
  return window['go']['wailsapp']['App']['GetWorkspacePersistenceLevel']();
}

export function GetWorkspaceSessionState(arg1) {
  return window['go']['wailsapp']['App']['GetWorkspaceSessionState'](arg1);
}

export function GetWorkspaceState() {
  return window['go']['wailsapp']['App']['GetWorkspaceState']();
}

export function GetWsPort() {
  return window['go']['wailsapp']['App']['GetWsPort']();
}

export function GetWsToken() {
  return window['go']['wailsapp']['App']['GetWsToken']();
}

export function HandleThemeToolRequest(arg1, arg2) {
  return window['go']['wailsapp']['App']['HandleThemeToolRequest'](arg1, arg2);
}

export function HasRecoveryPassword() {
  return window['go']['wailsapp']['App']['HasRecoveryPassword']();
}

export function ImportConnections(arg1, arg2) {
  return window['go']['wailsapp']['App']['ImportConnections'](arg1, arg2);
}

export function ImportProgramFontFiles(arg1) {
  return window['go']['wailsapp']['App']['ImportProgramFontFiles'](arg1);
}

export function ImportThemePackageFiles(arg1) {
  return window['go']['wailsapp']['App']['ImportThemePackageFiles'](arg1);
}

export function InstallRuntimeEnvironment(arg1) {
  return window['go']['wailsapp']['App']['InstallRuntimeEnvironment'](arg1);
}

export function InstallUnzip(arg1) {
  return window['go']['wailsapp']['App']['InstallUnzip'](arg1);
}

export function IsCustomTasksDir() {
  return window['go']['wailsapp']['App']['IsCustomTasksDir']();
}

export function IsPortableVersion() {
  return window['go']['wailsapp']['App']['IsPortableVersion']();
}

export function KillProcess(arg1, arg2) {
  return window['go']['wailsapp']['App']['KillProcess'](arg1, arg2);
}

export function ListConnectedSessions() {
  return window['go']['wailsapp']['App']['ListConnectedSessions']();
}

export function ListDir(arg1, arg2) {
  return window['go']['wailsapp']['App']['ListDir'](arg1, arg2);
}

export function ListExternalEditSessions() {
  return window['go']['wailsapp']['App']['ListExternalEditSessions']();
}

export function ListFTPBackups() {
  return window['go']['wailsapp']['App']['ListFTPBackups']();
}

export function ListOwnershipCandidates(arg1) {
  return window['go']['wailsapp']['App']['ListOwnershipCandidates'](arg1);
}

export function ListPortForwards(arg1) {
  return window['go']['wailsapp']['App']['ListPortForwards'](arg1);
}

export function ListProgramFonts() {
  return window['go']['wailsapp']['App']['ListProgramFonts']();
}

export function ListR2Backups() {
  return window['go']['wailsapp']['App']['ListR2Backups']();
}

export function ListSFTPBackups() {
  return window['go']['wailsapp']['App']['ListSFTPBackups']();
}

export function ListSerialPorts() {
  return window['go']['wailsapp']['App']['ListSerialPorts']();
}

export function ListThemePackages() {
  return window['go']['wailsapp']['App']['ListThemePackages']();
}

export function ListWebdavBackups() {
  return window['go']['wailsapp']['App']['ListWebdavBackups']();
}

export function MarkThemeToolConversationUserConfirmed(arg1) {
  return window['go']['wailsapp']['App']['MarkThemeToolConversationUserConfirmed'](arg1);
}

export function MigrateAITasksDir(arg1) {
  return window['go']['wailsapp']['App']['MigrateAITasksDir'](arg1);
}

export function Mkdir(arg1, arg2) {
  return window['go']['wailsapp']['App']['Mkdir'](arg1, arg2);
}

export function MoveItem(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['MoveItem'](arg1, arg2, arg3);
}

export function NetworkInfo(arg1) {
  return window['go']['wailsapp']['App']['NetworkInfo'](arg1);
}

export function OpenLocalPathInExplorer(arg1, arg2) {
  return window['go']['wailsapp']['App']['OpenLocalPathInExplorer'](arg1, arg2);
}

export function OpenRemoteFileInSystemEditor(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['OpenRemoteFileInSystemEditor'](arg1, arg2, arg3, arg4);
}

export function OpenRemoteFileWithEditor(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['OpenRemoteFileWithEditor'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenTerminal(arg1) {
  return window['go']['wailsapp']['App']['OpenTerminal'](arg1);
}

export function PingServer(arg1, arg2) {
  return window['go']['wailsapp']['App']['PingServer'](arg1, arg2);
}

export function PreviewDownloadConflicts(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['PreviewDownloadConflicts'](arg1, arg2, arg3, arg4);
}

export function PreviewSmartUncompressItem(arg1, arg2) {
  return window['go']['wailsapp']['App']['PreviewSmartUncompressItem'](arg1, arg2);
}

export function PreviewTombstoneConflicts() {
  return window['go']['wailsapp']['App']['PreviewTombstoneConflicts']();
}

export function PruneSyncTombstones(arg1) {
  return window['go']['wailsapp']['App']['PruneSyncTombstones'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['ReadFile'](arg1, arg2);
}

export function ReadPrivateKeyFile() {
  return window['go']['wailsapp']['App']['ReadPrivateKeyFile']();
}

export function ReconnectWithPassword(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['ReconnectWithPassword'](arg1, arg2, arg3, arg4);
}

export function ReloadMCPGlobalServers() {
  return window['go']['wailsapp']['App']['ReloadMCPGlobalServers']();
}

export function RenameConnectionGroup(arg1, arg2) {
  return window['go']['wailsapp']['App']['RenameConnectionGroup'](arg1, arg2);
}

export function RenameItem(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['RenameItem'](arg1, arg2, arg3);
}

export function ResetRecoveryPassword(arg1) {
  return window['go']['wailsapp']['App']['ResetRecoveryPassword'](arg1);
}

export function ResetTasksDir() {
  return window['go']['wailsapp']['App']['ResetTasksDir']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveDirectoryPath(arg1, arg2) {
  return window['go']['wailsapp']['App']['ResolveDirectoryPath'](arg1, arg2);
}

export function ResolveDownloadLocalPath(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ResolveDownloadLocalPath'](arg1, arg2, arg3);
}

export function ResolveDownloadPath(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['ResolveDownloadPath'](arg1, arg2, arg3, arg4);
}

export function ResolveMCPApproval(arg1, arg2) {
  return window['go']['wailsapp']['App']['ResolveMCPApproval'](arg1, arg2);
}

export function RestartMCPClientServer(arg1, arg2) {
  return window['go']['wailsapp']['App']['RestartMCPClientServer'](arg1, arg2);
}

export function RestartPortForwardForSession(arg1, arg2) {
  return window['go']['wailsapp']['App']['RestartPortForwardForSession'](arg1, arg2);
}

export function RestoreFromFTPFile(arg1) {
  return window['go']['wailsapp']['App']['RestoreFromFTPFile'](arg1);
}

export function RestoreFromFTPFileWithPassword(arg1, arg2) {
  return window['go']['wailsapp']['App']['RestoreFromFTPFileWithPassword'](arg1, arg2);
}

export function RestoreFromR2File(arg1) {
  return window['go']['wailsapp']['App']['RestoreFromR2File'](arg1);
}

export function RestoreFromR2FileWithPassword(arg1, arg2) {
  return window['go']['wailsapp']['App']['RestoreFromR2FileWithPassword'](arg1, arg2);
}

export function RestoreFromSFTPFile(arg1) {
  return window['go']['wailsapp']['App']['RestoreFromSFTPFile'](arg1);
}

export function RestoreFromSFTPFileWithPassword(arg1, arg2) {
  return window['go']['wailsapp']['App']['RestoreFromSFTPFileWithPassword'](arg1, arg2);
}

export function RestoreFromWebdavFile(arg1) {
  return window['go']['wailsapp']['App']['RestoreFromWebdavFile'](arg1);
}

export function RestoreFromWebdavFileWithPassword(arg1, arg2) {
  return window['go']['wailsapp']['App']['RestoreFromWebdavFileWithPassword'](arg1, arg2);
}

export function RetrySync() {
  return window['go']['wailsapp']['App']['RetrySync']();
}

export function SaveChmodDialogSettings(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveChmodDialogSettings'](arg1, arg2);
}

export function SaveCommandHistory(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveCommandHistory'](arg1, arg2);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveConnection'](arg1, arg2);
}

export function SaveCredential(arg1) {
  return window['go']['wailsapp']['App']['SaveCredential'](arg1);
}

export function SaveFTPConfig(arg1) {
  return window['go']['wailsapp']['App']['SaveFTPConfig'](arg1);
}

export function SaveGlobalCommandHistory(arg1) {
  return window['go']['wailsapp']['App']['SaveGlobalCommandHistory'](arg1);
}

export function SaveMCPEmbeddedFirecrawlAPIKey(arg1) {
  return window['go']['wailsapp']['App']['SaveMCPEmbeddedFirecrawlAPIKey'](arg1);
}

export function SaveMCPGlobalServer(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveMCPGlobalServer'](arg1, arg2);
}

export function SaveMCPOutputCompressionSettings(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveMCPOutputCompressionSettings'](arg1, arg2);
}

export function SaveParamHistory(arg1) {
  return window['go']['wailsapp']['App']['SaveParamHistory'](arg1);
}

export function SaveProxyNodes(arg1) {
  return window['go']['wailsapp']['App']['SaveProxyNodes'](arg1);
}

export function SaveQuickCommands(arg1) {
  return window['go']['wailsapp']['App']['SaveQuickCommands'](arg1);
}

export function SaveQuickCommandsLocal(arg1) {
  return window['go']['wailsapp']['App']['SaveQuickCommandsLocal'](arg1);
}

export function SaveR2Config(arg1) {
  return window['go']['wailsapp']['App']['SaveR2Config'](arg1);
}

export function SaveRuntimeEnvironmentSettings(arg1) {
  return window['go']['wailsapp']['App']['SaveRuntimeEnvironmentSettings'](arg1);
}

export function SaveSFTPConfig(arg1) {
  return window['go']['wailsapp']['App']['SaveSFTPConfig'](arg1);
}

export function SaveThemePackageSettings(arg1) {
  return window['go']['wailsapp']['App']['SaveThemePackageSettings'](arg1);
}

export function SaveTransferTuningSettings(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['SaveTransferTuningSettings'](arg1, arg2, arg3, arg4);
}

export function SaveWebdavConfig(arg1) {
  return window['go']['wailsapp']['App']['SaveWebdavConfig'](arg1);
}

export function SaveWorkspaceSessionState(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveWorkspaceSessionState'](arg1, arg2);
}

export function SaveWorkspaceState(arg1) {
  return window['go']['wailsapp']['App']['SaveWorkspaceState'](arg1);
}

export function SelectDownloadDirectory(arg1) {
  return window['go']['wailsapp']['App']['SelectDownloadDirectory'](arg1);
}

export function SelectDownloadFilePath(arg1, arg2) {
  return window['go']['wailsapp']['App']['SelectDownloadFilePath'](arg1, arg2);
}

export function SelectExternalEditor() {
  return window['go']['wailsapp']['App']['SelectExternalEditor']();
}

export function SelectImportFile() {
  return window['go']['wailsapp']['App']['SelectImportFile']();
}

export function SelectProgramFontFiles() {
  return window['go']['wailsapp']['App']['SelectProgramFontFiles']();
}

export function SelectTasksDirectory() {
  return window['go']['wailsapp']['App']['SelectTasksDirectory']();
}

export function SelectThemePackageFiles() {
  return window['go']['wailsapp']['App']['SelectThemePackageFiles']();
}

export function SelectUploadDirectory() {
  return window['go']['wailsapp']['App']['SelectUploadDirectory']();
}

export function SelectUploadFiles() {
  return window['go']['wailsapp']['App']['SelectUploadFiles']();
}

export function SetAutoSyncEnabled(arg1) {
  return window['go']['wailsapp']['App']['SetAutoSyncEnabled'](arg1);
}

export function SetChmodAutoApplyLastSettings(arg1) {
  return window['go']['wailsapp']['App']['SetChmodAutoApplyLastSettings'](arg1);
}

export function SetConnectionGroup(arg1, arg2) {
  return window['go']['wailsapp']['App']['SetConnectionGroup'](arg1, arg2);
}

export function SetConnectionOS(arg1, arg2) {
  return window['go']['wailsapp']['App']['SetConnectionOS'](arg1, arg2);
}

export function SetFileManagerAutoRefreshDisabled(arg1) {
  return window['go']['wailsapp']['App']['SetFileManagerAutoRefreshDisabled'](arg1);
}

export function SetFileManagerDoubleClickUncompressArchive(arg1) {
  return window['go']['wailsapp']['App']['SetFileManagerDoubleClickUncompressArchive'](arg1);
}

export function SetFileManagerMaxEditSize(arg1) {
  return window['go']['wailsapp']['App']['SetFileManagerMaxEditSize'](arg1);
}

export function SetFileManagerSmartUncompressConflictStrategy(arg1) {
  return window['go']['wailsapp']['App']['SetFileManagerSmartUncompressConflictStrategy'](arg1);
}

export function SetLiveWorkspaceState(arg1) {
  return window['go']['wailsapp']['App']['SetLiveWorkspaceState'](arg1);
}

export function SetRecoveryPassword(arg1) {
  return window['go']['wailsapp']['App']['SetRecoveryPassword'](arg1);
}

export function SetRememberWorkspace(arg1) {
  return window['go']['wailsapp']['App']['SetRememberWorkspace'](arg1);
}

export function SetSyncMode(arg1) {
  return window['go']['wailsapp']['App']['SetSyncMode'](arg1);
}

export function SetWebviewGpuDisabled(arg1) {
  return window['go']['wailsapp']['App']['SetWebviewGpuDisabled'](arg1);
}

export function SetWorkspacePersistenceLevel(arg1) {
  return window['go']['wailsapp']['App']['SetWorkspacePersistenceLevel'](arg1);
}

export function StartLocalPortForward(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['StartLocalPortForward'](arg1, arg2, arg3);
}

export function StartRemotePortForward(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['StartRemotePortForward'](arg1, arg2, arg3);
}

export function StopExternalEdit(arg1, arg2) {
  return window['go']['wailsapp']['App']['StopExternalEdit'](arg1, arg2);
}

export function StopPortForward(arg1) {
  return window['go']['wailsapp']['App']['StopPortForward'](arg1);
}

export function StopPortForwardForSession(arg1, arg2) {
  return window['go']['wailsapp']['App']['StopPortForwardForSession'](arg1, arg2);
}

export function SupportsWebviewGpuDisable() {
  return window['go']['wailsapp']['App']['SupportsWebviewGpuDisable']();
}

export function SyncAllProviders() {
  return window['go']['wailsapp']['App']['SyncAllProviders']();
}

export function SyncFromFTP() {
  return window['go']['wailsapp']['App']['SyncFromFTP']();
}

export function SyncFromR2() {
  return window['go']['wailsapp']['App']['SyncFromR2']();
}

export function SyncFromSFTP() {
  return window['go']['wailsapp']['App']['SyncFromSFTP']();
}

export function SyncFromWebdav() {
  return window['go']['wailsapp']['App']['SyncFromWebdav']();
}

export function SyncWithRecoveryPassword(arg1) {
  return window['go']['wailsapp']['App']['SyncWithRecoveryPassword'](arg1);
}

export function SystemInfo(arg1) {
  return window['go']['wailsapp']['App']['SystemInfo'](arg1);
}

export function SystemInfoLite(arg1) {
  return window['go']['wailsapp']['App']['SystemInfoLite'](arg1);
}

export function TestFTPConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['TestFTPConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function TestFTPConnectionWithCertificateApproval(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailsapp']['App']['TestFTPConnectionWithCertificateApproval'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function TestR2Connection(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['TestR2Connection'](arg1, arg2, arg3, arg4);
}

export function TestSFTPConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailsapp']['App']['TestSFTPConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function TestSFTPConnectionWithHostKeyApproval(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['wailsapp']['App']['TestSFTPConnectionWithHostKeyApproval'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function TestWebdavConnection(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['TestWebdavConnection'](arg1, arg2, arg3);
}

export function ToggleMCPClientServer(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ToggleMCPClientServer'](arg1, arg2, arg3);
}

export function ToggleMCPClientServerDisabledForPrompts(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ToggleMCPClientServerDisabledForPrompts'](arg1, arg2, arg3);
}

export function ToggleMCPClientServerToolDisabledForPrompts(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['ToggleMCPClientServerToolDisabledForPrompts'](arg1, arg2, arg3, arg4);
}

export function UncompressItem(arg1, arg2) {
  return window['go']['wailsapp']['App']['UncompressItem'](arg1, arg2);
}

export function UncompressItemWithStrategy(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['UncompressItemWithStrategy'](arg1, arg2, arg3);
}

export function UpdateApp(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['UpdateApp'](arg1, arg2, arg3);
}

export function UpdateMCPClientServerTimeout(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['UpdateMCPClientServerTimeout'](arg1, arg2, arg3);
}

export function UploadChunkBase64(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['UploadChunkBase64'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['UploadFile'](arg1, arg2);
}

export function UploadFileContent(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['UploadFileContent'](arg1, arg2, arg3, arg4);
}

export function UploadFileContentBase64(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['UploadFileContentBase64'](arg1, arg2, arg3, arg4);
}

export function UploadLocalDir(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['UploadLocalDir'](arg1, arg2, arg3);
}

export function UploadLocalFile(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['UploadLocalFile'](arg1, arg2, arg3);
}

export function UploadLocalPathsCompressed(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['UploadLocalPathsCompressed'](arg1, arg2, arg3, arg4, arg5);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['WriteFile'](arg1, arg2, arg3);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['wailsapp']['App']['WriteTerminal'](arg1, arg2);
}

export function WriteWsOutput(arg1, arg2) {
  return window['go']['wailsapp']['App']['WriteWsOutput'](arg1, arg2);
}
